Repository containerd/nerdctl, pull requests merged in 2021-09, with the labels that each got.

#323 nerdctl inspect --format
  README.md
  cmd/nerdctl/container_inspect.go
  cmd/nerdctl/image_inspect.go
Labels: enhancement, status/merge-on-green

#340 Adding missing "name" param to macos command in README.md
  README.md
Labels: documentation

#327 nerdctl events --format
  README.md
  cmd/nerdctl/events.go
Labels: enhancement

#324 fix inspect show more than one number
  cmd/nerdctl/inspect.go
Labels: bug

#357 Fix image output
  cmd/nerdctl/load.go
  go.mod
  go.sum
Labels: kind/external

#401 Clarify the list of the experimental features
  README.md
  cmd/nerdctl/run.go
  docs/experimental.md
Labels: documentation
