Repository containerd/nerdctl, pull requests merged in 2021-12, with the labels that each got.

#585 CI: test-integration-rootless: increase timeout from 30 to 60
  .github/workflows/test.yml
Labels: area/ci

#580 Add test matrix for windows ctrd versions
  .cirrus.yml
  hack/configure-windows-ci.ps1
Labels: area/ci, platform/Windows

#593 compose: support ulimits
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#603 Add overlaybd support
  pkg/imgutil/imgutil.go
Labels: enhancement, impact/major

#606 [Carry 556] feat: cosign sign
  Dockerfile
  README.md
  cmd/nerdctl/pull.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/push.go
  cmd/nerdctl/run_windows.go
  docs/cosign.md
  docs/experimental.md
  pkg/imgutil/imgutil.go
Labels: area/cosign

#556 feat: cosign sign
  Dockerfile
  README.md
  cmd/nerdctl/pull.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/push.go
  cmd/nerdctl/run_windows.go
  docs/cosign.md
  docs/experimental.md
  pkg/imgutil/imgutil.go
Labels: enhancement, impact/major, area/cosign

#612 Refacto cobra cmd
  cmd/nerdctl/commit.go
  cmd/nerdctl/container_inspect.go
  cmd/nerdctl/events.go
  cmd/nerdctl/exec.go
  cmd/nerdctl/image_inspect.go
  cmd/nerdctl/images.go
  cmd/nerdctl/inspect.go
  cmd/nerdctl/kill.go
  cmd/nerdctl/logs.go
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_inspect.go
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/pause.go
  cmd/nerdctl/port.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/rmi.go
  cmd/nerdctl/run.go
  cmd/nerdctl/save.go
  cmd/nerdctl/start.go
  cmd/nerdctl/stop.go
  cmd/nerdctl/tag.go
  cmd/nerdctl/top.go
  cmd/nerdctl/unpause.go
  cmd/nerdctl/volume_create.go
  cmd/nerdctl/volume_inspect.go
  cmd/nerdctl/volume_rm.go
  cmd/nerdctl/wait.go
Labels: kind/refactor

#602 add scale flag for compose up
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_logs.go
  cmd/nerdctl/compose_ps.go
  cmd/nerdctl/compose_up.go
  cmd/nerdctl/compose_up_linux_test.go
  pkg/composer/composer.go
  pkg/composer/container.go
  pkg/composer/down.go
  pkg/composer/logs.go
  pkg/composer/up.go
  pkg/composer/up_service.go
Labels: area/compose

#620 ipfs registry: use buffer when read from IPFS to reduce requests
  pkg/ipfs/registry.go
Labels: area/ipfs

#614 Cirrus CI: remove "Windows 1.5 tests" due to flakiness
  .cirrus.yml
Labels: area/ci

#617 Add compose kill command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_kill.go
  cmd/nerdctl/compose_kill_linux_test.go
  cmd/nerdctl/compose_logs.go
  pkg/composer/kill.go
Labels: enhancement, area/compose

#621 support specifying service name for compose pull/push
  cmd/nerdctl/compose_pull.go
  cmd/nerdctl/compose_pull_linux_test.go
  cmd/nerdctl/compose_push.go
  pkg/composer/pull.go
  pkg/composer/push.go
Labels: enhancement, area/compose

#615 CI: move cgroup v2 tests to Cirrus
  .cirrus.yml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/etc_systemd_system_user@.service.d_delegate.conf
  hack/Vagrantfile.fedora
Labels: area/ci

#626 split generateNetOpts func
  cmd/nerdctl/run.go
Labels: kind/refactor

#625 Refactor tests
  .cirrus.yml
  Dockerfile.d/test-integration-rootless.sh
  cmd/nerdctl/build_test.go
  cmd/nerdctl/commit_test.go
  cmd/nerdctl/container_inspect_linux_test.go
  cmd/nerdctl/exec_linux_test.go
  cmd/nerdctl/exec_test.go
  cmd/nerdctl/image_convert_test.go
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/ipfs_build_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/logs_test.go
  cmd/nerdctl/multi_platform_linux_test.go
  cmd/nerdctl/network_inspect_test.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/push_linux_test.go
  cmd/nerdctl/run_cgroup_linux_test.go
  cmd/nerdctl/run_linux_test.go
  cmd/nerdctl/run_mount_linux_test.go
  cmd/nerdctl/run_network_linux_test.go
  cmd/nerdctl/run_restart_linux_test.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/save_linux_test.go
  cmd/nerdctl/stats_linux_test.go
  cmd/nerdctl/stop_linux_test.go
  cmd/nerdctl/top_linux_test.go
  cmd/nerdctl/volume_inspect_test.go
  cmd/nerdctl/wait_test.go
  pkg/testutil/testutil.go
Labels: area/ci

#628 add verify cosign for run command
  README.md
  cmd/nerdctl/pull.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_verify_linux_test.go
Labels: enhancement, impact/major, area/cosign

#632 add services/volumes/hash flag for config command
  README.md
  cmd/nerdctl/compose_config.go
  cmd/nerdctl/compose_config_test.go
  pkg/composer/config.go
Labels: enhancement, area/compose

#638 tests: fix RequiresBuild
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/run_verify_linux_test.go
Labels: area/ci

#635 Support loading `nerdctl.toml` (`$NERDCTL_TOML`)
  README.md
  cmd/nerdctl/main.go
  cmd/nerdctl/main_test.go
  docs/config.md
  docs/dir.md
  docs/faq.md
  go.mod
  pkg/defaults/defaults_freebsd.go
  pkg/defaults/defaults_linux.go
  pkg/defaults/defaults_windows.go
Labels: enhancement, impact/major

#646 Add nerdctl create command
  README.md
  cmd/nerdctl/client.go
  cmd/nerdctl/container.go
  cmd/nerdctl/create.go
  cmd/nerdctl/create_linux_test.go
  cmd/nerdctl/main.go
  cmd/nerdctl/run.go
Labels: enhancement

#650 Cirrus CI: force TCP DNS to deflake rootless tests
  .cirrus.yml
  Dockerfile.d/test-integration-rootless.sh
  cmd/nerdctl/compose_kill_linux_test.go
Labels: area/rootless, area/ci

#653 add label flag for build
  README.md
  cmd/nerdctl/build.go
  cmd/nerdctl/build_test.go
Labels: enhancement
