Repository containerd/nerdctl, pull requests merged in 2021-11, with the labels that each got.

#197 Windows Part 2 - run windows containers
  .cirrus.yml
  README.md
  cmd/nerdctl/client.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_cgroup_linux_test.go
  cmd/nerdctl/run_freebsd.go
  cmd/nerdctl/run_linux.go
  cmd/nerdctl/run_mount.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/run_user_windows_test.go
  cmd/nerdctl/run_windows.go
  hack/configure-windows-ci.ps1
  pkg/defaults/defaults_windows.go
  pkg/testutil/testutil.go
Labels: enhancement, platform/Windows

#73 setup stats command
  README.md
  cmd/nerdctl/main.go
  cmd/nerdctl/stats.go
  cmd/nerdctl/stats_freebsd.go
  cmd/nerdctl/stats_linux.go
  cmd/nerdctl/stats_test.go
  cmd/nerdctl/stats_windows.go
  go.mod
  go.sum
  pkg/eventutil/eventutil.go
  pkg/statsutil/stats.go
  pkg/statsutil/stats_linux.go
Labels: enhancement

#505 Enable image distribution on IPFS
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/go-ipfs-0.10.0
  Dockerfile.d/test-integration-etc_containerd-stargz-grpc_config.toml
  Dockerfile.d/test-integration-ipfs-offline.service
  Dockerfile.d/test-integration-rootless.sh
  README.md
  cmd/nerdctl/commit.go
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_up_test.go
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/image_cryptutil.go
  cmd/nerdctl/images.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  cmd/nerdctl/push_test.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/save.go
  cmd/nerdctl/tag.go
  docs/experimental.md
  docs/ipfs.md
  extras/rootless/containerd-rootless-setuptool.sh
  go.mod
  go.sum
  pkg/idutil/imagewalker/imagewalker.go
  pkg/imgutil/imgutil.go
  pkg/ipfs/image.go
  pkg/referenceutil/referenceutil.go
Labels: enhancement, impact/major

#524 Unfork spf13/{cobra, pflag}
  README.md
  cmd/nerdctl/apparmor_linux.go
  cmd/nerdctl/build.go
  cmd/nerdctl/compose.go
  cmd/nerdctl/container.go
  cmd/nerdctl/image.go
  cmd/nerdctl/main.go
  cmd/nerdctl/namespace.go
  cmd/nerdctl/network.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  cmd/nerdctl/run.go
  cmd/nerdctl/system.go
  cmd/nerdctl/volume.go
  go.mod
  go.sum
Labels: priority/high

#554 ipfs: rootless: Allow optionally exposing ports used by ipfs
  docs/ipfs.md
  extras/rootless/containerd-rootless-setuptool.sh
Labels: documentation, area/rootless

#565 nerdctl-full/README.md: Clarify the license of go-ipfs
  Dockerfile
Labels: documentation, area/ipfs

#552 support overriding image CMD on commit
  cmd/nerdctl/commit.go
  pkg/imgutil/commit/commit.go
Labels: enhancement

#575 cmd/nerdctl: support (backport) zstdchunked convert
  README.md
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/image_convert_test.go
Labels: enhancement, impact/major

#576 tests: fix Windows failure
  cmd/nerdctl/image_convert_test.go
Labels: priority/high, area/ci

#561 MAINTAINERS: add Kohei Tokunaga as a COMMITTER
  MAINTAINERS
Labels: area/project

#562 MAINTAINERS: add James Sturtevant as a REVIEWER
  MAINTAINERS
Labels: area/project

#563 MAINTAINERS: promote Fahed Dorgaa from a REVIEWER to a COMMITTER
  MAINTAINERS
Labels: area/project

#579 [Carry 578] Troubleshooting doc
  .github/ISSUE_TEMPLATE.md
  README.md
  docs/faq.md
Labels: documentation

#533 Windows: run CI with containerd 1.5.8
  hack/configure-windows-ci.ps1
Labels: area/ci, platform/Windows
