Repository containerd/nerdctl, pull requests merged in 2021-08, with the labels that each got.

#311 run with pidfile option
  README.md
  cmd/nerdctl/run.go
  pkg/labels/labels.go
  pkg/ocihook/ocihook.go
Labels: status/merge-on-green, impact/changelog

#305 Environment variables in Compose
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_up_test.go
  go.mod
  go.sum
  pkg/composer/composer.go
  pkg/composer/projectloader/projectloader.go
  pkg/composer/serviceparser/build_test.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: enhancement, area/compose, impact/changelog

#316 load: import all platforms (--all-platforms)
  cmd/nerdctl/load.go
Labels: status/merge-on-green, impact/changelog

#320 docs/ocicrypt.md: update for containerd 1.5
  docs/ocicrypt.md
Labels: documentation

#319 nerdctl (ps|images|volume ls|network ls|version) --format
  README.md
  cmd/nerdctl/fmtutil.go
  cmd/nerdctl/images.go
  cmd/nerdctl/network_ls.go
  cmd/nerdctl/ps.go
  cmd/nerdctl/version.go
  cmd/nerdctl/volume_ls.go
  pkg/infoutil/infoutil.go
  pkg/inspecttypes/dockercompat/info.go
Labels: impact/changelog
