Repository containerd/nerdctl, pull requests merged in 2021-10, with the labels that each got.

#402 Makefile: clean up FreeBSD/amd64 nerdctl
  Makefile
Labels: area/ci, platform/FreeBSD

#413 nerdctl: add `--env-file` to `exec`
  README.md
  cmd/nerdctl/exec.go
Labels: enhancement

#477 Fix parsing flags with comma (`nerdctl run --env FOO=foo1,foo2`)
  cmd/nerdctl/build.go
  cmd/nerdctl/compose_build.go
  cmd/nerdctl/exec.go
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/load.go
  cmd/nerdctl/network_create.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_mount.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/save.go
  cmd/nerdctl/volume_create.go
Labels: priority/high
