Repository containerd/nerdctl, pull requests merged in 2022-03, with the labels that each got.

#867 CI: temporarily remove FreeBSD integration tests
  .cirrus.yml
  docs/freebsd.md
Labels: area/ci, platform/FreeBSD

#866 Attempt to deflake TestPushInsecureWithLogin
  cmd/nerdctl/push.go
Labels: area/ci

#824 Support automatic host port assignment
  cmd/nerdctl/run_network_linux_test.go
  pkg/portutil/port_allocate_linux.go
  pkg/portutil/port_allocate_others.go
  pkg/portutil/portutil.go
  pkg/portutil/portutil_test.go
  pkg/portutil/procnet/procnet.go
  pkg/portutil/procnet/procnet_linux.go
  pkg/portutil/procnet/procnetd_test.go
Labels: enhancement, impact/major

#873 pkg/portutil: improve rootless error message
  pkg/portutil/portutil.go
Labels: area/rootless

#877 Add macvlan/ipvlan doc for cni
  docs/cni.md
Labels: documentation

#881 Update the README.md to remind people to upgrade the Go version
  README.md
Labels: documentation

#903 refactor netutil
  cmd/nerdctl/completion.go
  cmd/nerdctl/compose.go
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_inspect.go
  cmd/nerdctl/network_ls.go
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/run_network.go
  pkg/netutil/netutil.go
  pkg/ocihook/ocihook.go
Labels: kind/refactor

#910 Windows CI: install git
  hack/configure-windows-ci.ps1
Labels: area/ci, platform/Windows

#911 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  SECURITY.md
Labels: area/project

#916 CI: remove integration test with contianerd v1.4.5
  .github/workflows/test.yml
Labels: area/ci

#858 rootless: Support BuildKit containerd worker
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/buildkit-v0.10.0
  Dockerfile.d/SHA256SUMS.d/buildkit-v0.9.3
  Dockerfile.d/test-integration-buildkit-nerdctl-test.service
  Dockerfile.d/test-integration-rootless.sh
  README.md
  cmd/nerdctl/build.go
  cmd/nerdctl/build_test.go
  cmd/nerdctl/builder.go
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/ipfs_build_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/main.go
  cmd/nerdctl/multi_platform_linux_test.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/run_mount_linux_test.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/run_verify_linux_test.go
  cmd/nerdctl/system.go
  extras/rootless/containerd-rootless-setuptool.sh
  pkg/buildkitutil/buildkitutil.go
  pkg/testutil/testutil.go
Labels: area/rootless, impact/major

#874 enhance namespace management
  README.md
  cmd/nerdctl/namespace.go
  cmd/nerdctl/namespace_create.go
  cmd/nerdctl/namespace_freebsd.go
  cmd/nerdctl/namespace_inspect.go
  cmd/nerdctl/namespace_linux.go
  cmd/nerdctl/namespace_rm.go
  cmd/nerdctl/namespace_update.go
  cmd/nerdctl/namespace_windows.go
  pkg/inspecttypes/native/namespace.go
Labels: enhancement, impact/major

#923 docs: clarify that P2P image distribution (IPFS) is completely optional
  README.md
  docs/ipfs.md
  go.mod
Labels: documentation, area/ipfs

#918 avoid nil authconfig && display warning msg for unencrypted passwd
  cmd/nerdctl/login.go
Labels: area/login

#838 CNI: switch away from `isolation` plugin to `firewall` plugin with `ingressPolicy`
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/cni-isolation-v0.0.4
  README.md
  cmd/nerdctl/network_create.go
  docs/cni.md
  go.mod
  go.sum
  pkg/netutil/cni_plugin_unix.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_unix.go
  pkg/netutil/netutil_unix_test.go
  pkg/netutil/netutil_windows.go
Labels: impact/major

#929 CI: set fail-fast to false
  .github/workflows/test.yml
Labels: area/ci

#926 Support assign static IP address in `compose up` by using ipv4_address field
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/run_network_linux_test.go
  pkg/composer/serviceparser/serviceparser.go
Labels: area/compose

#938 docs: clarify availability of optional features
  docs/build.md
  docs/compose.md
  docs/cosign.md
  docs/gpu.md
  docs/ipfs.md
  docs/multi-platform.md
  docs/ocicrypt.md
  docs/stargz.md
Labels: documentation

#942 Remove orphan containers before the service has be started
  pkg/composer/up.go
Labels: area/compose
