Repository containerd/nerdctl, pull requests merged in 2022-05, with the labels that each got.

#999 enhancement restart policy
  README.md
  cmd/nerdctl/info.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_restart.go
  cmd/nerdctl/run_restart_linux_test.go
  cmd/nerdctl/start.go
  cmd/nerdctl/stop.go
  cmd/nerdctl/volume_rm.go
  go.mod
  go.sum
  pkg/formatter/formatter.go
  pkg/infoutil/infoutil.go
  pkg/inspecttypes/dockercompat/dockercompat.go
  pkg/testutil/testutil.go
Labels: enhancement

#860 supporting COMPOSE_FILE environment variable
  cmd/nerdctl/compose_config_test.go
  pkg/composer/composer.go
Labels: enhancement, area/compose

#1049 Support interactive debugging of Dockerfile
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/buildg-v0.0.3
  README.md
  cmd/nerdctl/builder.go
  cmd/nerdctl/builder_linux_test.go
  docs/builder-debug.md
  docs/experimental.md
Labels: enhancement, impact/major

#1070 compose: enable entrypoint as stringArray
  cmd/nerdctl/run.go
  docs/compose.md
  pkg/composer/serviceparser/serviceparser.go
Labels: area/compose

#1061 CI: use GHA ubuntu-22.04 for cgroup2 tests
  .cirrus.yml
  .github/workflows/ghcr-image-build-and-publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  cmd/nerdctl/run_cgroup_linux_test.go
Labels: area/ci
