Repository containerd/nerdctl, pull requests merged in 2022-02, with the labels that each got.

#768 docs/registry.md: jfrog repo
  docs/registry.md
Labels: documentation

#784 MAINTAINERS: add Ye Sijun (Junnplus) as a REVIEWER
  MAINTAINERS
Labels: area/project

#774 purge useless login func
  cmd/nerdctl/login.go
Labels: status/merge-on-green

#805 Fix push progress always waiting
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
  pkg/imgutil/push/push.go
Labels: status/merge-on-green

#802 refactor compose and support multi compose files
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_config_test.go
  cmd/nerdctl/main.go
  pkg/composer/composer.go
  pkg/composer/up_network.go
  pkg/composer/up_service.go
  pkg/composer/up_volume.go
  pkg/testutil/compose.go
Labels: area/compose, impact/major

#789 fixe image size
  cmd/nerdctl/images.go
Labels: status/merge-on-green

#810 nerdctl-full: add bypass4netns
  Dockerfile
  README.md
  cmd/nerdctl/run.go
  docs/rootless.md
  extras/rootless/containerd-rootless-setuptool.sh
  pkg/labels/labels.go
  pkg/ocihook/ocihook.go
Labels: area/rootless, area/bypass4netns

#816 fix vol name for test
  cmd/nerdctl/run_mount_linux_test.go
Labels: area/ci

#801 add --mount option for nerdctl run
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_mount.go
  cmd/nerdctl/run_mount_linux_test.go
  pkg/mountutil/mountutil_freebsd.go
  pkg/mountutil/mountutil_linux.go
  pkg/mountutil/mountutil_windows.go
Labels: impact/major

#821 CI: relax timeout
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/ci

#830 fix null authConfig bug
  cmd/nerdctl/login.go
Labels: bug, priority/high

#836 Add macvlan/ipvlan network driver
  README.md
  cmd/nerdctl/network_create_unix.go
  pkg/netutil/cni_plugin_unix.go
  pkg/netutil/netutil_unix.go
Labels: enhancement, impact/major

#842 Separate network code
  cmd/nerdctl/run.go
  cmd/nerdctl/run_network.go
Labels: kind/refactor
