Repository containerd/nerdctl, pull requests merged in 2022-07, with the labels that each got.

#1163 feat: makes nerdctl available to pull/run nydus images
  go.mod
  go.sum
  pkg/imgutil/imgutil.go
Labels: enhancement

#1174 Support multiple tags in nerdctl
  cmd/nerdctl/build.go
  cmd/nerdctl/build_test.go
Labels: enhancement

#1180 support container prune
  README.md
  cmd/nerdctl/container.go
  cmd/nerdctl/container_prune.go
  cmd/nerdctl/container_prune_linux_test.go
  cmd/nerdctl/create.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/run.go
Labels: enhancement

#1189 docs: add nydus snapshotter description
  README.md
  docs/nydus.md
Labels: documentation

#1204 fix broken deps for dbus
  Dockerfile
Labels: area/ci

#1201 TestRunCgroupV1: fix cgroup version check
  cmd/nerdctl/run_cgroup_linux_test.go
Labels: area/ci

#1210 update unimplemented flags for run
  README.md
Labels: documentation

#1212 Add document about overlaybd
  README.md
  docs/overlaybd.md
Labels: documentation

#1220 wait for detached container running before exec
  cmd/nerdctl/commit_test.go
  cmd/nerdctl/exec_linux_test.go
  cmd/nerdctl/exec_test.go
  cmd/nerdctl/ps_linux_test.go
  cmd/nerdctl/rename_linux_test.go
  cmd/nerdctl/run_cgroup_linux_test.go
  cmd/nerdctl/run_mount_linux_test.go
  pkg/testutil/testutil.go
Labels: area/ci

#1221 Log matches of log paths to understand TestRunWithJsonFileLogDriver flakiness
  cmd/nerdctl/run_test.go
Labels: area/ci

#1230 README.md: clean up
  README.md
Labels: documentation

#1239 README.md: clean up
  README.md
Labels: documentation

#1232 Remove duplicate host record when update the DNS
  cmd/nerdctl/compose_up_linux_test.go
  pkg/dnsutil/hostsstore/updater.go
Labels: enhancement

#1214 support --network=container:<contaienr> for sharing network namespace
  README.md
  cmd/nerdctl/restart.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_network.go
  cmd/nerdctl/run_network_linux_test.go
  cmd/nerdctl/start.go
  pkg/netutil/nettype/nettype.go
  pkg/ocihook/ocihook.go
Labels: enhancement

#1251 small refactor for rmAction
  cmd/nerdctl/container_prune.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/run.go
Labels: kind/refactor

#1252 test fluentd log driver without build image
  cmd/nerdctl/run_linux_test.go
Labels: area/ci

#1256 rewrite test of run with init flag
  cmd/nerdctl/run.go
  cmd/nerdctl/run_linux_test.go
Labels: area/ci

#1258 remove useless args from load
  cmd/nerdctl/build.go
  cmd/nerdctl/load.go
Labels: kind/refactor

#1271 Refactor: Abstract the way to handle remote snapshotter
  pkg/imgutil/imgutil.go
  pkg/imgutil/snapshotter.go
  pkg/imgutil/snapshotter_test.go
Labels: kind/refactor

#1270 Pass https://index.docker.io/v1/ to GetAuthConfig() for Docker Hub
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
Labels: area/login
