Repository containerd/nerdctl, pull requests merged in 2022-06, with the labels that each got.

#1062 Implement journald logging driver
  README.md
  cmd/nerdctl/logs.go
  cmd/nerdctl/logs_test.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_test.go
  go.mod
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/logging.go
  pkg/testutil/testutil.go
Labels: area/logging

#1073 Implement fluentd logging driver
  README.md
  cmd/nerdctl/run_linux_test.go
  go.mod
  go.sum
  pkg/logging/fluentd_logger.go
  pkg/logging/fluentd_logger_test.go
  pkg/logging/logging.go
  pkg/testutil/testutil_linux.go
Labels: area/logging

#1124 Add GitLab Container Registry to Registry Docs
  docs/registry.md
Labels: documentation, area/login

#1119 fix log-driver name not check error
  cmd/nerdctl/run.go
Labels: area/logging

#1132 Initialize the log file to fix `nerdctl compose up` error
  cmd/nerdctl/logs.go
  cmd/nerdctl/run.go
  go.mod
  go.sum
  pkg/infoutil/infoutil.go
  pkg/logging/fluentd_logger.go
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/logging.go
Labels: area/logging

#1140 add umask
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_user.go
  cmd/nerdctl/run_user_linux_test.go
Labels: enhancement

#1141 CI: unparallelize TestRunAddHost
  cmd/nerdctl/run_linux_test.go
Labels: area/ci

#1121 MAINTAINERS: add Zheao Li as a REVIEWER
  MAINTAINERS
Labels: area/project

#1169 support dns-search and dns-opt
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_network.go
  cmd/nerdctl/run_network_linux_test.go
Labels: enhancement

#1164 show name for images
  README.md
  cmd/nerdctl/images.go
  cmd/nerdctl/images_test.go
  pkg/idutil/imagewalker/imagewalker.go
Labels: enhancement

#1136 Fixed gosimple errors in issue #1134
  .golangci.yml
  cmd/nerdctl/exec.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/ipfs_registry_up.go
  cmd/nerdctl/main_unix.go
  cmd/nerdctl/run_linux_test.go
  cmd/nerdctl/run_network.go
  cmd/nerdctl/run_network_linux_test.go
  pkg/ipfs/registry.go
  pkg/mountutil/mountutil.go
  pkg/statsutil/stats.go
Labels: area/ci
