Repository containerd/nerdctl, pull requests merged in 2022-04, with the labels that each got.

#970 CI: relax timeout
  Dockerfile
Labels: area/ci

#968 Deflake TestComposeKill
  cmd/nerdctl/compose_kill_linux_test.go
Labels: area/ci

#978 feat: container image build ci for push image to github registry
  .github/workflows/ghcr-image-build-and-publish.yml
Labels: area/ci

#948 Support --init argument in nerdctl run command
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/tini-v0.19.0
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_linux_test.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/testutil/testutil_linux.go
Labels: enhancement

#991 CI: upload go-mod-vendor.tar.gz as a backup
  Makefile
Labels: area/ci

#990 Import NOTICE from Docker/Moby
  NOTICE
  cmd/nerdctl/top.go
  extras/rootless/containerd-rootless-setuptool.sh
  extras/rootless/containerd-rootless.sh
  pkg/buildkitutil/buildkitutil.go
  pkg/composer/config.go
  pkg/inspecttypes/dockercompat/dockercompat.go
  pkg/inspecttypes/dockercompat/info.go
  pkg/mountutil/mountutil_linux.go
  pkg/resolvconf/resolvconf.go
  pkg/strutil/strutil.go
Labels: documentation

#994 Add flag ipfs-address to push to remote IPFS node
  README.md
  cmd/nerdctl/push.go
Labels: enhancement, area/ipfs

#995 [Carry 643] cp cmd
  README.md
  cmd/nerdctl/container.go
  cmd/nerdctl/cp.go
  cmd/nerdctl/cp_linux.go
  cmd/nerdctl/cp_linux_test.go
  cmd/nerdctl/main.go
  cmd/nerdctl/main_freebsd.go
  cmd/nerdctl/main_linux.go
  cmd/nerdctl/main_windows.go
  pkg/tarutil/tarutil.go
Labels: enhancement

#1006 fixes #1004 : Build image only when changes merged to master
  .github/workflows/ghcr-image-build-and-publish.yml
Labels: area/ci

#1011 info: add --mode=native to show full plugin info
  README.md
  cmd/nerdctl/info.go
  pkg/infoutil/infoutil.go
  pkg/inspecttypes/native/info.go
Labels: enhancement

#1015 Makefile: avoid flattening `nerdctl-X.Y.Z-go-mod-vendor.tar.gz`
  Makefile
Labels: area/ci
