Repository containerd/nerdctl, pull requests merged in 2022-09, with the labels that each got.

#1342 Feat: support filter argument for `nerdctl ps` command
  README.md
  cmd/nerdctl/container_lsutil.go
  cmd/nerdctl/ps.go
  cmd/nerdctl/ps_linux_test.go
Labels: enhancement, kind/feature

#1351 Randomize container names in compose run
  pkg/composer/run.go
  pkg/idgen/idgen.go
Labels: area/compose

#1315 Make the ServerAddress optional for the main docker registry.
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
Labels: area/login

#1354 Implements logURI to support 3rd party ctrd shim logger
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_test.go
Labels: area/logging

#1379 Change login and logout msg from Docker registry to container registry
  README.md
  cmd/nerdctl/login.go
  cmd/nerdctl/logout.go
Labels: documentation, area/logging

#1377 Support `syslog` driver for nerdctl
  README.md
  cmd/nerdctl/run_log_driver_syslog_test.go
  go.mod
  go.sum
  pkg/logging/logging.go
  pkg/logging/syslog_logger.go
  pkg/testutil/testsyslog/testsyslog.go
Labels: area/logging

#1402 Makefile: Set VERSION & REVISION only if unset
  Makefile
Labels: enhancement
