Repository containerd/nerdctl, pull requests merged in 2022-11, with the labels that each got.

#1481 Enable on-failure and unless-stopped restart policy in compose
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#1479 Enable service args for `compose build`
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_build.go
  cmd/nerdctl/compose_build_linux_test.go
  cmd/nerdctl/compose_kill.go
  cmd/nerdctl/compose_logs.go
  cmd/nerdctl/compose_ps.go
  cmd/nerdctl/compose_pull.go
  cmd/nerdctl/compose_push.go
  cmd/nerdctl/compose_up.go
  pkg/composer/build.go
Labels: area/compose

#1484 Improve the documenation of 'compose build --progress'
  README.md
  cmd/nerdctl/compose_build.go
Labels: documentation

#1491 Small fix on bridge ipam
  docs/cni.md
Labels: documentation

#1492 Add more specific description about restart and stop command
  README.md
Labels: documentation

#1468 Refactor `nerdctl logs` functionality to pkg/logging.
  cmd/nerdctl/login_linux_test.go
  cmd/nerdctl/logs.go
  cmd/nerdctl/logs_test.go
  cmd/nerdctl/run.go
  go.mod
  go.sum
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/jsonfile/jsonfile.go
  pkg/logging/log_viewer.go
  pkg/logging/logging.go
  pkg/testutil/testutil.go
Labels: kind/refactor, area/logging

#1503 Refactor stop/rm containers in compose
  pkg/composer/run.go
  pkg/composer/stop.go
  pkg/composer/up_service.go
Labels: area/compose, kind/refactor

#1508 Add cosign in compose
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_run_linux_test.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  docs/cosign.md
  pkg/composer/composer.go
  pkg/composer/pull.go
  pkg/composer/push.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/up_service.go
  pkg/cosignutil/cosignutil.go
Labels: area/compose, area/cosign

#1518 Support for ephemeral ports
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#1527 golangci: add revive check
  .golangci.yml
  cmd/nerdctl/build.go
  cmd/nerdctl/commit.go
  cmd/nerdctl/container_prune.go
  cmd/nerdctl/cp_linux.go
  cmd/nerdctl/create.go
  cmd/nerdctl/exec.go
  cmd/nerdctl/image_prune.go
  cmd/nerdctl/images.go
  cmd/nerdctl/logs.go
  cmd/nerdctl/namespace_create.go
  cmd/nerdctl/network_prune.go
  cmd/nerdctl/ps.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_linux.go
  cmd/nerdctl/run_linux_test.go
  cmd/nerdctl/run_mount.go
  cmd/nerdctl/run_network_linux_test.go
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/tag.go
  cmd/nerdctl/volume_prune.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/eventutil/eventutil.go
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
  pkg/imgutil/imgutil.go
  pkg/logging/json_logger.go
  pkg/logging/jsonfile/jsonfile.go
  pkg/maputil/maputil.go
  pkg/mountutil/volumestore/volumestore.go
  pkg/netutil/netutil.go
  pkg/ocihook/ocihook.go
  pkg/testutil/testutil.go
Labels: area/ci, kind/refactor

#1529 relax "containerIP assignment is not supported in rootless mode" error
  pkg/ocihook/ocihook.go
Labels: area/rootless

#1531 Use service label to check orphan container
  pkg/composer/orphans.go
Labels: area/compose, kind/refactor

#1552 binfmt: support /proc/sys/fs/binfmt_misc/rosetta
  pkg/platformutil/binfmt.go
Labels: platform/ARM, platform/macOS

#1534 Add `compose rm` command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_rm.go
  cmd/nerdctl/compose_rm_linux_test.go
  pkg/composer/rm.go
Labels: area/compose

#1557 Add yaml linter in workflow
  .cirrus.yml
  .github/dependabot.yml
  .github/workflows/ghcr-image-build-and-publish.yml
  .github/workflows/test.yml
  .golangci.yml
  .yamllint
  examples/nerdctl-ipfs-registry-kubernetes/ipfs-cluster/nerdctl-ipfs-registry.yaml
  examples/nerdctl-ipfs-registry-kubernetes/ipfs-stargz-snapshotter/nerdctl-ipfs-registry.yaml
  examples/nerdctl-ipfs-registry-kubernetes/ipfs/nerdctl-ipfs-registry.yaml
Labels: area/ci, kind/refactor

#1563 Add support for filtering images by labels.
  README.md
  cmd/nerdctl/images.go
  cmd/nerdctl/images_test.go
  pkg/imgutil/imgutil.go
Labels: enhancement, area/compose

#1555 Add `compose images` command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_images.go
  cmd/nerdctl/compose_images_linux_test.go
Labels: area/compose

#1554 fix network creation behavior
  cmd/nerdctl/compose.go
  cmd/nerdctl/run_network.go
  pkg/netutil/netutil.go
  pkg/ocihook/ocihook.go
Labels: kind/refactor

#1562 Refactor remove containers in compose
  pkg/composer/down.go
  pkg/composer/rm.go
  pkg/composer/run.go
  pkg/composer/up.go
Labels: area/compose

#1539 MAINTAINERS: promote Zheao Li from a REVIEWER to a COMMITTER
  MAINTAINERS
Labels: area/project

#1540 MAINTAINERS: add Hanchin Hsieh (yuchanns) as a REVIEWER
  MAINTAINERS
Labels: area/project

#1544 MAINTAINERS: promote Ye Sijun (junnplus) from a REVIEWER to a COMMITTER
  MAINTAINERS
Labels: area/project

#1545 MAINTAINERS: add Manu Gupta (manugupt1) as a REVIEWER
  MAINTAINERS
Labels: area/project
