Repository containerd/nerdctl, pull requests merged in 2022-12, with the labels that each got.

#1573 go.mod: add a comment about indirect dependency on `github.com/btcsuite/btcd/btcec` (NOT bitcoin daemon itself)
  go.mod
Labels: documentation, dependencies, area/ipfs

#1569 Add an extra validation when remove the network
  README.md
  cmd/nerdctl/container_lsutil.go
  cmd/nerdctl/network_prune.go
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/network_rm_linux_test.go
  pkg/netutil/netutil.go
Labels: area/network

#1519 Refactor the logging driver process function
  pkg/logging/fluentd_logger.go
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/jsonfile/jsonfile.go
  pkg/logging/logging.go
  pkg/logging/syslog_logger.go
Labels: area/logging

#1583 Deflake TestCompletion
  cmd/nerdctl/completion_linux_test.go
Labels: area/ci

#1590 docs: explain how to get rootless containerd socket address
  docs/faq.md
Labels: documentation, area/rootless

#1567 Add compose ps json
  README.md
  cmd/nerdctl/compose_ps.go
  cmd/nerdctl/compose_ps_linux_test.go
  cmd/nerdctl/ps.go
  pkg/formatter/formatter.go
  pkg/portutil/portutil.go
  pkg/portutil/portutil_test.go
Labels: area/compose

#1588 allow container network_mode in compose
  pkg/composer/serviceparser/serviceparser.go
Labels: area/compose

#1591 doctoc docs/faq.md
  docs/faq.md
Labels: documentation

#1599 deflake network tests
  cmd/nerdctl/network_create_linux_test.go
  cmd/nerdctl/network_rm_linux_test.go
Labels: area/ci

#1598 Add `compose exec` command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_exec.go
  cmd/nerdctl/compose_exec_linux_test.go
  cmd/nerdctl/exec.go
  pkg/composer/exec.go
Labels: area/compose

#1611 deflake TestNetworkRemoveById
  cmd/nerdctl/network_rm_linux_test.go
Labels: area/ci

#1614 Fix env handling in 2 exec commands
  cmd/nerdctl/compose_exec_linux_test.go
  cmd/nerdctl/exec.go
  cmd/nerdctl/exec_test.go
  cmd/nerdctl/run.go
  pkg/composer/exec.go
  pkg/flagutil/flagutil.go
  pkg/flagutil/flagutil_test.go
Labels: area/compose

#1621 Add compose pause and unpause commands
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_pause.go
  cmd/nerdctl/compose_pause_linux_test.go
Labels: area/compose

#1609 Add `compose top` command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_top.go
  cmd/nerdctl/compose_top_linux_test.go
Labels: area/compose

#1628 Add `compose port` command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_port.go
  cmd/nerdctl/compose_port_linux_test.go
  cmd/nerdctl/port.go
  pkg/composer/port.go
  pkg/containerutil/containerutil.go
Labels: area/compose

#1626 Upgrade indirect dependancy go-libp2p-core to v0.20.1
  go.mod
  go.sum
Labels: area/ipfs

#1624 CI: add gotestsum with --rerun-fails=2
  Dockerfile
  pkg/testutil/testutil.go
Labels: area/ci

#1618 Fix: Deleting multiple networks stops at first delete fail
  cmd/nerdctl/network_rm.go
  pkg/idutil/netwalker/netwalker.go
Labels: area/network

#1638 Fix bugs in compose stop and restart
  cmd/nerdctl/compose_restart_linux_test.go
  cmd/nerdctl/compose_stop_linux_test.go
  pkg/composer/restart.go
  pkg/composer/stop.go
Labels: area/compose

#1640 go.mod: accelerated-container-image v0.5.3-0.20221209054854-fbdabc5a08b6
  go.mod
  go.sum
Labels: dependencies

#1641 go.mod: github.com/ipfs/go-merkledag v0.8.1
  go.mod
  go.sum
Labels: dependencies, area/ipfs

#1643 Make titles Bold in `nerdctl` output
  cmd/nerdctl/main.go
Labels: enhancement

#1648 [GHCR image] feat: support for multi-arch image build support
  .github/workflows/ghcr-image-build-and-publish.yml
Labels: area/ci

#1650 defalke testRunWithJsonFileLogDriver*
  go.mod
  go.sum
Labels: area/ci

#1656 Add compose start command
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_ps.go
  cmd/nerdctl/compose_start.go
  cmd/nerdctl/compose_start_linux_test.go
  cmd/nerdctl/compose_top.go
  pkg/composer/composer.go
  pkg/containerutil/containerutil.go
Labels: area/compose

#1664 Add RequireExecutable to testutil
  cmd/nerdctl/compose_run_linux_test.go
  cmd/nerdctl/image_convert_linux_test.go
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/logs_test.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/run_verify_linux_test.go
  pkg/testutil/testutil.go
Labels: area/ci

#1669 Clean up boilerplate code in test
  cmd/nerdctl/compose_config_test.go
  cmd/nerdctl/compose_images_linux_test.go
  cmd/nerdctl/compose_kill_linux_test.go
  cmd/nerdctl/compose_pause_linux_test.go
  cmd/nerdctl/compose_restart_linux_test.go
  cmd/nerdctl/compose_rm_linux_test.go
  cmd/nerdctl/compose_start_linux_test.go
  cmd/nerdctl/compose_stop_linux_test.go
  cmd/nerdctl/run_test.go
  cmd/nerdctl/run_user_linux_test.go
  cmd/nerdctl/start_test.go
  pkg/testutil/testutil.go
Labels: area/ci

#1668 Add compose create
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_create.go
  cmd/nerdctl/compose_create_linux_test.go
  cmd/nerdctl/compose_start.go
  pkg/composer/create.go
Labels: area/compose

#1649 MAINTAINERS: add Jin Dong(djdongjin) as a REVIEWER
  MAINTAINERS
Labels: area/project

#1671 SetInterspersed(false) for compose run
  cmd/nerdctl/compose_run.go
Labels: area/compose, area/cobra

#1653 IPFS: use ipfs binary instead of library
  README.md
  cmd/nerdctl/build.go
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_build.go
  cmd/nerdctl/compose_run.go
  cmd/nerdctl/ipfs_build_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/ipfs_registry.go
  cmd/nerdctl/ipfs_registry_down.go
  cmd/nerdctl/ipfs_registry_linux_test.go
  cmd/nerdctl/ipfs_registry_serve.go
  cmd/nerdctl/ipfs_registry_up.go
  cmd/nerdctl/main.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/push.go
  docs/ipfs.md
  extras/rootless/containerd-rootless-setuptool.sh
  go.mod
  go.sum
  pkg/composer/build.go
  pkg/composer/run.go
  pkg/composer/up_service.go
  pkg/ipfs/image.go
  pkg/ipfs/registry.go
Labels: area/ipfs

#1681 remove processed TODO
  pkg/dnsutil/hostsstore/updater.go
Labels: documentation

#1771 setPlatformOptions: Change signature
  cmd/nerdctl/run.go
  cmd/nerdctl/run_freebsd.go
  cmd/nerdctl/run_linux.go
  cmd/nerdctl/run_windows.go
Labels: kind/refactor

#1683 run: Add --uts flag
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_linux.go
  cmd/nerdctl/run_linux_test.go
Labels: enhancement

#1366 feat: add `--remove-orphans` flag to `compose down`
  README.md
  cmd/nerdctl/compose_down.go
  cmd/nerdctl/compose_down_linux_test.go
  pkg/composer/down.go
Labels: area/compose

#1779 [Refactor]: Move fmtutil from cmd to pkg/formatter
  cmd/nerdctl/apparmor_ls_linux.go
  cmd/nerdctl/container_inspect.go
  cmd/nerdctl/events.go
  cmd/nerdctl/history.go
  cmd/nerdctl/image_inspect.go
  cmd/nerdctl/images.go
  cmd/nerdctl/info.go
  cmd/nerdctl/namespace_inspect.go
  cmd/nerdctl/network_inspect.go
  cmd/nerdctl/network_ls.go
  cmd/nerdctl/ps.go
  cmd/nerdctl/stats.go
  cmd/nerdctl/version.go
  cmd/nerdctl/volume_inspect.go
  cmd/nerdctl/volume_ls.go
  pkg/formatter/common.go
Labels: kind/refactor

#1785 Filter dangling images using image filters.
  cmd/nerdctl/images.go
  cmd/nerdctl/images_test.go
  pkg/imgutil/imgutil.go
Labels: enhancement
