Repository containerd/nerdctl, pull requests merged in 2022-08, with the labels that each got.

#1286 go-ipfs (0.13.1) -> Kubo (0.14.0)
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/go-ipfs-v0.13.1
  Dockerfile.d/SHA256SUMS.d/kubo-v0.14.0
  docs/ipfs.md
  examples/nerdctl-ipfs-registry-kubernetes/README.md
Labels: area/ipfs

#1285 doc: fix missed doc and help msg about firewall plugin
  README.md
  cmd/nerdctl/network_create.go
  pkg/netutil/netutil_unix.go
Labels: documentation

#1289 Fix `can't get final child's PID from pipe` on rootless (v0.22.1 regression)
  cmd/nerdctl/run_linux.go
Labels: priority/high

#1338 golangci-lint: remove deprecated linters
  .github/workflows/test.yml
  .golangci.yml
Labels: area/ci
