Repository containerd/nerdctl, pull requests merged in 2022-01, with the labels that each got.

#660 remove bridge network interface after network rm
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/network_rm_freebsd.go
  cmd/nerdctl/network_rm_linux.go
  cmd/nerdctl/network_rm_windows.go
Labels: status/merge-on-green

#659 README.md: Mention install with homebrew
  README.md
Labels: documentation

#652 support network ipam for compose
  cmd/nerdctl/compose_up_linux_test.go
  pkg/composer/up_network.go
Labels: bug, area/compose

#663 fix doc
  README.md
Labels: documentation

#662 Dockerfile: update Ubuntu to 21.10
  Dockerfile
Labels: area/ci

#664 support labels in compose up --build
  pkg/composer/serviceparser/build.go
  pkg/composer/serviceparser/build_test.go
Labels: area/compose

#656 add docs for using CNI plugins with nerdctl
  README.md
  cmd/nerdctl/run.go
  docs/cni.md
  pkg/netutil/netutil.go
Labels: documentation

#676 ipfs registry: allow timeout and retry
  README.md
  cmd/nerdctl/ipfs_registry_serve.go
  cmd/nerdctl/ipfs_registry_up.go
  pkg/ipfs/registry.go
Labels: area/ipfs

#688 remove io/ioutil
  pkg/dnsutil/hostsstore/updater.go
Labels: kind/refactor

#642 Support `/etc/containerd/certs.d/<HOST:PORT>/hosts.toml`
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/login.go
  cmd/nerdctl/login_linux_test.go
  cmd/nerdctl/main.go
  cmd/nerdctl/multi_platform_linux_test.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/pull_linux_test.go
  cmd/nerdctl/push.go
  cmd/nerdctl/push_linux_test.go
  cmd/nerdctl/run_network_linux_test.go
  cmd/nerdctl/run_restart_linux_test.go
  cmd/nerdctl/run_verify_linux_test.go
  cmd/nerdctl/stop_linux_test.go
  docs/config.md
  docs/faq.md
  docs/registry.md
  go.mod
  go.sum
  pkg/defaults/defaults_freebsd.go
  pkg/defaults/defaults_linux.go
  pkg/defaults/defaults_windows.go
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
  pkg/imgutil/imgutil.go
  pkg/testutil/nettestutil/nettestutil.go
  pkg/testutil/testca/testca.go
  pkg/testutil/testregistry/testregistry_linux.go
Labels: enhancement, impact/major

#673 Add --pause=false option to commit command.
  README.md
  cmd/nerdctl/commit.go
  cmd/nerdctl/commit_test.go
  pkg/imgutil/commit/commit.go
Labels: enhancement

#672 refactor network generate
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_rm.go
  docs/cni.md
  pkg/netutil/cni_plugin.go
  pkg/netutil/cni_plugin_unix.go
  pkg/netutil/cni_plugin_windows.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_unix.go
  pkg/netutil/netutil_windows.go
Labels: kind/refactor

#689 add nerdctl run cpuset-mems,cpu-quota,cpu-period support
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_cgroup_linux.go
  cmd/nerdctl/run_cgroup_linux_test.go
Labels: enhancement, status/merge-on-green

#691 CI: containerd 1.5.8 -> 1.5.9
  .github/workflows/test.yml
Labels: area/ci

#693 run: automatically generate a container name from image ref
  cmd/nerdctl/ps.go
  cmd/nerdctl/run.go
  pkg/referenceutil/referenceutil.go
  pkg/referenceutil/referenceutil_test.go
Labels: enhancement, impact/major

#695 Add gateway and ip-range flag for network create
  README.md
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_inspect_test.go
  pkg/inspecttypes/dockercompat/dockercompat.go
  pkg/netutil/cni_plugin.go
  pkg/netutil/cni_plugin_unix.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_test.go
  pkg/netutil/netutil_unix.go
  pkg/netutil/netutil_windows.go
Labels: enhancement

#678 Add example manifest of `nerdctl ipfs registry` on Kubernetes
  examples/nerdctl-ipfs-registry-kubernetes/README.md
  examples/nerdctl-ipfs-registry-kubernetes/bootstrap.yaml.sh
  examples/nerdctl-ipfs-registry-kubernetes/nerdctl-ipfs-registry.yaml
Labels: documentation, enhancement, area/ipfs

#705 add cgroupv1 test
  cmd/nerdctl/run_cgroup_linux_test.go
Labels: enhancement, area/ci

#714 improve error message of ipfs api address could not be found
  cmd/nerdctl/ipfs_registry_serve.go
Labels: documentation, status/merge-on-green, area/ipfs

#696 add update resource
  README.md
  cmd/nerdctl/container.go
  cmd/nerdctl/main.go
  cmd/nerdctl/run_cgroup_linux_test.go
  cmd/nerdctl/update.go
Labels: enhancement

#700 Add driver and opt flags for network create
  README.md
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_create_linux_test.go
  cmd/nerdctl/network_create_unix.go
  cmd/nerdctl/network_create_windows.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_unix.go
  pkg/netutil/netutil_windows.go
Labels: enhancement

#749 docs/registry.md: add guide for managed services (ECR, ACR, Docker Hub, GHCR, pkg.dev, GCR, quay.io)
  README.md
  docs/registry.md
Labels: documentation
