Repository containerd/nerdctl, pull requests merged in 2023-01, with the labels that each got.

#1782 run: Add cgroup-parent flag
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_cgroup_linux.go
  cmd/nerdctl/run_cgroup_linux_test.go
Labels: enhancement

#1773 Refactor the volume ls command flagging process
  cmd/nerdctl/volume.go
  cmd/nerdctl/volume_ls.go
  pkg/api/types/volume_types.go
  pkg/cmd/volume/ls.go
  pkg/cmd/volume/volume.go
Labels: kind/refactor

#1793 [Refactor] Move the Config Struct from cmd/main.go to pkg/config
  cmd/nerdctl/main.go
  pkg/api/types/global.go
  pkg/config/config.go
Labels: kind/refactor

#1799 CI: Pass GITHUB_TOKEN to containerd/project-checks
  .github/workflows/test.yml
Labels: area/ci

#1792 [Refactor] Refactor the build subcommand flagging process
  .gitignore
  cmd/nerdctl/build.go
  pkg/api/types/build_types.go
  pkg/cmd/build/build.go
Labels: kind/refactor

#1795 Refactor the volume flagging process
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/volume_create.go
  cmd/nerdctl/volume_inspect.go
  cmd/nerdctl/volume_ls.go
  cmd/nerdctl/volume_prune.go
  cmd/nerdctl/volume_rm.go
  pkg/api/types/volume_types.go
  pkg/cmd/volume/create.go
  pkg/cmd/volume/inspect.go
  pkg/cmd/volume/ls.go
  pkg/cmd/volume/prune.go
  pkg/cmd/volume/rm.go
Labels: kind/refactor

#1820 [Refactor] Refactor the load command flagging process
  cmd/nerdctl/load.go
  pkg/api/types/load_types.go
  pkg/cmd/load/load.go
Labels: kind/refactor

#1818 [Refactor] Refactor the compose command flagging process
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_build.go
  cmd/nerdctl/compose_config.go
  cmd/nerdctl/compose_create.go
  cmd/nerdctl/compose_down.go
  cmd/nerdctl/compose_exec.go
  cmd/nerdctl/compose_images.go
  cmd/nerdctl/compose_kill.go
  cmd/nerdctl/compose_logs.go
  cmd/nerdctl/compose_pause.go
  cmd/nerdctl/compose_port.go
  cmd/nerdctl/compose_ps.go
  cmd/nerdctl/compose_pull.go
  cmd/nerdctl/compose_push.go
  cmd/nerdctl/compose_restart.go
  cmd/nerdctl/compose_rm.go
  cmd/nerdctl/compose_run.go
  cmd/nerdctl/compose_start.go
  cmd/nerdctl/compose_stop.go
  cmd/nerdctl/compose_top.go
  cmd/nerdctl/compose_up.go
  pkg/cmd/compose/compose.go
  pkg/composer/composer.go
Labels: area/compose, kind/refactor

#1821 [Refactor] Refactor the images command flagging process
  cmd/nerdctl/images.go
  cmd/nerdctl/ps.go
  pkg/api/types/image_type.go
  pkg/cmd/image/list.go
Labels: kind/refactor

#1801 ipfs: allow configuring ipfs daemon address
  README.md
  cmd/nerdctl/compose.go
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/run.go
  docs/ipfs.md
  go.mod
  go.sum
  pkg/cmd/compose/compose.go
  pkg/composer/composer.go
  pkg/ipfs/image.go
  pkg/testutil/testutil_linux.go
Labels: area/ipfs

#1824 [Refactor] Refactor all the GlobalCommandOptions from pointer to value reference
  cmd/nerdctl/container_prune.go
  cmd/nerdctl/create.go
  cmd/nerdctl/flagutil.go
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/image_inspect.go
  cmd/nerdctl/images.go
  cmd/nerdctl/info.go
  cmd/nerdctl/load.go
  cmd/nerdctl/login.go
  cmd/nerdctl/network_prune.go
  cmd/nerdctl/pull.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/run.go
  cmd/nerdctl/run_cgroup_linux.go
  cmd/nerdctl/run_freebsd.go
  cmd/nerdctl/run_linux.go
  cmd/nerdctl/run_mount.go
  cmd/nerdctl/run_network.go
  cmd/nerdctl/run_runtime.go
  cmd/nerdctl/run_windows.go
  cmd/nerdctl/stats.go
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/update.go
  cmd/nerdctl/version.go
  cmd/nerdctl/volume.go
  cmd/nerdctl/volume_ls.go
  pkg/api/types/build_types.go
  pkg/api/types/volume_types.go
  pkg/cmd/compose/compose.go
Labels: kind/refactor

#1838 Fix rename command readme
  README.md
Labels: documentation

#795 Add Windows Hostprocess flag
  README.md
  cmd/nerdctl/run.go
  cmd/nerdctl/run_windows.go
  cmd/nerdctl/run_windows_test.go
  hack/configure-windows-ci.ps1
Labels: enhancement, platform/Windows/Non-WSL2, impact/major

#1843 CI: ensure that ./pkg/... is decoupled from the CLI packages
  .github/workflows/test.yml
  hack/verify-pkg-isolation.sh
Labels: area/ci

#1840 mv pkg/cmd/load/load.go pkg/cmd/image/load.go
  cmd/nerdctl/load.go
  pkg/cmd/image/load.go
Labels: kind/refactor

#1841 mv pkg/cmd/build pkg/cmd/builder
  cmd/nerdctl/build.go
  pkg/cmd/builder/build.go
Labels: kind/refactor

#1842 pkg/cmd: Ls -> List
  cmd/nerdctl/apparmor_ls_linux.go
  cmd/nerdctl/volume_ls.go
  pkg/api/types/apparmor_types.go
  pkg/api/types/volume_types.go
  pkg/cmd/apparmor/list_linux.go
  pkg/cmd/volume/list.go
Labels: kind/refactor

#1846 go.mod: github.com/docker/docker v23.0.0-rc.2+incompatible
  go.mod
  go.sum
Labels: dependencies

#1851 [Refactor] Refactor network list
  cmd/nerdctl/network_ls.go
  pkg/api/types/network_types.go
  pkg/cmd/network/list.go
Labels: kind/refactor

#1834 Refactor nerdctl rm
  cmd/nerdctl/container_prune.go
  cmd/nerdctl/rm.go
  cmd/nerdctl/run.go
  pkg/api/types/container_types.go
  pkg/cmd/container/remove.go
Labels: kind/refactor

#1857 [Refactor] Move exit_coder from cmd to pkg/errutil
  cmd/nerdctl/main.go
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/run.go
  cmd/nerdctl/start.go
  pkg/errutil/exit_coder.go
Labels: kind/refactor

#1862 [refactor] Adjust code style for apparmor command
  cmd/nerdctl/apparmor_inspect_linux.go
  cmd/nerdctl/apparmor_ls_linux.go
  cmd/nerdctl/apparmor_unload_linux.go
  pkg/api/types/apparmor_types.go
  pkg/cmd/apparmor/inspect_linux.go
  pkg/cmd/apparmor/list_linux.go
  pkg/cmd/apparmor/unload_linux.go
Labels: kind/refactor

#1853 [Refactor] Refactor the image_* command flagging process
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/image_cryptutil.go
  cmd/nerdctl/image_inspect.go
  cmd/nerdctl/inspect.go
  cmd/nerdctl/push.go
  pkg/api/types/image_type.go
  pkg/api/types/image_types.go
  pkg/cmd/image/convert.go
  pkg/cmd/image/crypt.go
  pkg/cmd/image/inspect.go
  pkg/cmd/image/push.go
Labels: kind/refactor

#1858 [refactor] Adjust the code style in `pkg/cmd/volume/*`
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/volume_create.go
  cmd/nerdctl/volume_inspect.go
  cmd/nerdctl/volume_ls.go
  cmd/nerdctl/volume_prune.go
  cmd/nerdctl/volume_rm.go
  pkg/api/types/volume_types.go
  pkg/cmd/volume/create.go
  pkg/cmd/volume/inspect.go
  pkg/cmd/volume/list.go
  pkg/cmd/volume/prune.go
  pkg/cmd/volume/rm.go
Labels: kind/refactor

#1863 [Refactor] Refactor the namespace command flagging process
  cmd/nerdctl/namespace_create.go
  cmd/nerdctl/namespace_inspect.go
  cmd/nerdctl/namespace_rm.go
  cmd/nerdctl/namespace_update.go
  pkg/api/types/namespace_types.go
  pkg/cmd/namespace/common.go
  pkg/cmd/namespace/create.go
  pkg/cmd/namespace/inspect.go
  pkg/cmd/namespace/namespace_freebsd.go
  pkg/cmd/namespace/namespace_linux.go
  pkg/cmd/namespace/namespace_windows.go
  pkg/cmd/namespace/remove.go
  pkg/cmd/namespace/update.go
Labels: kind/refactor

#1867 Increase CI timeout to reduce failure due to timeout
  .github/workflows/test.yml
  Dockerfile
Labels: area/ci

#1850 Refactor container inspect
  cmd/nerdctl/container_inspect.go
  pkg/api/types/container_types.go
  pkg/cmd/container/inspect.go
Labels: kind/refactor

#1847 add support logs for namespace k8s.io
  cmd/nerdctl/logs.go
  pkg/api/types/cri/metadata_types.go
  pkg/labels/k8slabels/k8slabels.go
  pkg/logging/cri_logger.go
  pkg/logging/cri_logger_test.go
  pkg/logging/log_viewer.go
  pkg/logging/tail/tail.go
  pkg/logging/tail/tail_test.go
Labels: kind/feature, area/logging

#1837 refactor: consolidate main logic of volume.List into volume.Volumes
  cmd/nerdctl/volume_ls.go
  pkg/cmd/volume/list.go
Labels: kind/refactor

#1869 refactor: image tag flagging process
  cmd/nerdctl/image_tag.go
  pkg/api/types/image_types.go
  pkg/cmd/image/tag.go
Labels: kind/refactor

#1852 [Refactor] Refactor images pull command
  cmd/nerdctl/pull.go
  cmd/nerdctl/run.go
  pkg/api/types/pull_types.go
  pkg/cmd/image/pull.go
Labels: kind/refactor

#1880 Move command reference to a separate doc
  README.md
  docs/command-reference.md
Labels: documentation

#1848 Add Windows HyperV container mode
  cmd/nerdctl/run.go
  cmd/nerdctl/run_windows.go
  cmd/nerdctl/run_windows_test.go
  docs/command-reference.md
Labels: platform/Windows/Non-WSL2

#1882 [Refactor] Move getContainerNetNSPath from cmd to pkg/containerutil
  cmd/nerdctl/run_network.go
  cmd/nerdctl/start.go
  pkg/containerutil/containerutil.go
Labels: kind/refactor

#1822 Refactor the network command flagging process
  cmd/nerdctl/network_create.go
  cmd/nerdctl/network_inspect.go
  cmd/nerdctl/network_prune.go
  cmd/nerdctl/network_rm.go
  cmd/nerdctl/system_prune.go
  pkg/api/types/network_types.go
  pkg/cmd/network/create.go
  pkg/cmd/network/inspect.go
  pkg/cmd/network/prune.go
  pkg/cmd/network/remove.go
Labels: kind/refactor

#1891 [Refactor] move withBindMountHostProcfs from cmd to pkg/containerutil.
  cmd/nerdctl/run.go
  cmd/nerdctl/run_linux.go
  pkg/containerutil/containerutil.go
Labels: kind/refactor

#1894 cmd/nerdctl: withBindMountHostIPC: slight refactor
  cmd/nerdctl/run.go
Labels: kind/refactor

#1861 refactor: login flagging process
  cmd/nerdctl/login.go
  pkg/api/types/login_types.go
  pkg/cmd/login/login.go
  pkg/cmd/login/login_unix.go
  pkg/cmd/login/login_windows.go
Labels: kind/refactor

#1897 refactor: move stopContainer to containerutil
  cmd/nerdctl/restart.go
  cmd/nerdctl/stop.go
  pkg/containerutil/containerutil.go
Labels: kind/refactor

#1898 [Refactor] refactor commit flagging process
  cmd/nerdctl/commit.go
  pkg/api/types/container_types.go
  pkg/cmd/container/commit.go
Labels: kind/refactor

#1892 [Refactor] refactor rmi flagging process
  cmd/nerdctl/rmi.go
  pkg/api/types/image_types.go
  pkg/cmd/image/remove.go
Labels: kind/refactor

#1902 [Refactor] Move reconfigNetContainer and reconfigPIDContainer from cm…
  cmd/nerdctl/start.go
  pkg/containerutil/config.go
Labels: kind/refactor

#1887 refactor: pass an io.Writer to image.List
  cmd/nerdctl/images.go
  pkg/api/types/image_types.go
  pkg/cmd/image/list.go
Labels: kind/refactor

#1881 refactor: container logs flagging process
  cmd/nerdctl/container_logs.go
  cmd/nerdctl/container_logs_test.go
  pkg/api/types/container_types.go
  pkg/cmd/container/logs.go
Labels: kind/refactor

#1905 mv pkg/cmd/info/info.go pkg/cmd/system/info.go
  cmd/nerdctl/info.go
  pkg/cmd/system/info.go
Labels: kind/refactor

#1904 [Refactor] Refactor the IPFS command flagging process
  cmd/nerdctl/ipfs_registry_serve.go
  pkg/api/types/ipfs_types.go
  pkg/cmd/ipfs/registry_serve.go
Labels: kind/refactor, area/ipfs

#1864 [Refactor] Refactor the container start command flagging process
  cmd/nerdctl/compose_start.go
  cmd/nerdctl/container_restart.go
  cmd/nerdctl/container_start.go
  pkg/api/types/container_types.go
  pkg/cmd/container/start.go
  pkg/containerutil/containerutil.go
Labels: kind/refactor

#1919 Update readme for dangling image support
  docs/command-reference.md
Labels: documentation

#1910 Optimize inspect commands
  cmd/nerdctl/container_inspect.go
  cmd/nerdctl/image_inspect.go
  cmd/nerdctl/inspect.go
  pkg/api/types/container_types.go
  pkg/cmd/container/inspect.go
  pkg/cmd/image/inspect.go
Labels: kind/refactor

#1878 refactor container top
  cmd/nerdctl/compose_top.go
  cmd/nerdctl/container_top.go
  pkg/api/types/container_types.go
  pkg/cmd/container/top.go
Labels: kind/refactor

#1883 [Refactor] refactor exec flagging process
  cmd/nerdctl/container_exec.go
  cmd/nerdctl/container_run.go
  pkg/api/types/container_types.go
  pkg/cmd/container/exec.go
  pkg/cmd/container/exec_freebsd.go
  pkg/cmd/container/exec_linux.go
  pkg/cmd/container/exec_windows.go
  pkg/cmd/container/run_user.go
  pkg/flagutil/flagutil.go
Labels: kind/refactor

#1920 [Refactor] Refactor the (container) pause command flagging process
  cmd/nerdctl/compose_pause.go
  cmd/nerdctl/container_pause.go
  pkg/api/types/container_types.go
  pkg/cmd/container/pause.go
  pkg/containerutil/containerutil.go
Labels: kind/refactor

#1908 [Refactor] Refactor the new client outside pkg/cmd.
  cmd/nerdctl/builder_build.go
  cmd/nerdctl/container_commit.go
  cmd/nerdctl/container_kill.go
  cmd/nerdctl/container_logs.go
  cmd/nerdctl/container_remove.go
  cmd/nerdctl/container_stop.go
  cmd/nerdctl/image_convert.go
  cmd/nerdctl/image_cryptutil.go
  cmd/nerdctl/image_list.go
  cmd/nerdctl/image_load.go
  cmd/nerdctl/image_pull.go
  cmd/nerdctl/image_push.go
  cmd/nerdctl/image_remove.go
  cmd/nerdctl/image_tag.go
  cmd/nerdctl/namespace_create.go
  cmd/nerdctl/namespace_inspect.go
  cmd/nerdctl/namespace_remove.go
  cmd/nerdctl/namespace_update.go
  cmd/nerdctl/network_prune.go
  cmd/nerdctl/network_remove.go
  cmd/nerdctl/system_info.go
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/volume_prune.go
  cmd/nerdctl/volume_remove.go
  pkg/cmd/builder/build.go
  pkg/cmd/container/commit.go
  pkg/cmd/container/kill.go
  pkg/cmd/container/logs.go
  pkg/cmd/container/remove.go
  pkg/cmd/container/stop.go
  pkg/cmd/image/convert.go
  pkg/cmd/image/crypt.go
  pkg/cmd/image/list.go
  pkg/cmd/image/load.go
  pkg/cmd/image/pull.go
  pkg/cmd/image/push.go
  pkg/cmd/image/remove.go
  pkg/cmd/image/tag.go
  pkg/cmd/namespace/create.go
  pkg/cmd/namespace/inspect.go
  pkg/cmd/namespace/remove.go
  pkg/cmd/namespace/update.go
  pkg/cmd/network/prune.go
  pkg/cmd/network/remove.go
  pkg/cmd/system/info.go
  pkg/cmd/volume/prune.go
  pkg/cmd/volume/rm.go
Labels: kind/refactor

#1916 refactor: system events flagging process
  cmd/nerdctl/system_events.go
  pkg/api/types/system_types.go
  pkg/cmd/system/events.go
Labels: kind/refactor

#1899 [Refactor] refactor container restart flagging process
  cmd/nerdctl/container_restart.go
  pkg/api/types/container_types.go
  pkg/cmd/container/restart.go
Labels: kind/refactor

#1917 ipfs: move to `net/http`-based implementation instead of binary-based one
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/stargz-snapshotter-v0.13.0
  Dockerfile.d/SHA256SUMS.d/stargz-snapshotter-v0.14.1
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/ipfs_build_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/ipfs_registry_linux_test.go
  docs/ipfs.md
  go.mod
  go.sum
  pkg/cmd/compose/compose.go
  pkg/cmd/image/pull.go
  pkg/cmd/image/push.go
  pkg/ipfs/image.go
  pkg/ipfs/registry.go
Labels: area/ipfs

#1943 compose: show detailed errors again
  cmd/nerdctl/compose_up_test.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/up_service.go
Labels: priority/high, area/compose

#1951 go.mod: github.com/containerd/accelerated-container-image v0.6.0
  go.mod
  go.sum
Labels: dependencies, go

#1958 Mark `cri` log viewer as experimental
  README.md
  cmd/nerdctl/container_logs.go
  docs/experimental.md
  pkg/cmd/container/logs.go
  pkg/logging/log_viewer.go
Labels: area/logging, area/kubernetes

#1959 docs: fix internal links to other Markdown docs.
  docs/command-reference.md
Labels: documentation
