Repository containerd/nerdctl, pull requests merged in 2023-08, with the labels that each got.

#2405 Add lease and remove special case
  .cirrus.yml
  pkg/cmd/container/run_mount.go
Labels: platform/Windows/Non-WSL2

#2410 .cirrus.yml: fix FreeBSD CI failure
  .cirrus.yml
Labels: area/ci, platform/FreeBSD

#2418 CI: move FreeBSD and Windows tests to GHA
  .cirrus.yml
  .github/workflows/test.yml
  .gitignore
  Vagrantfile.freebsd
  cmd/nerdctl/container_run_network_windows_test.go
  cmd/nerdctl/container_run_windows_test.go
  hack/configure-windows-ci.ps1
  pkg/testutil/testutil_windows.go
Labels: area/ci, platform/FreeBSD, platform/Windows/Non-WSL2

#2423 CI: Windows: enable Hyper-V containers
  .github/workflows/test.yml
Labels: area/ci, platform/Windows/Non-WSL2

#2425 FreeBSD: Linux Container Support and BuildKit Integration
  docs/freebsd.md
  pkg/buildkitutil/buildkitutil.go
Labels: platform/FreeBSD

#2427 Support Docker 23.0 compatibility
  .github/workflows/test.yml
  cmd/nerdctl/builder_build_test.go
  cmd/nerdctl/compose_up_test.go
  cmd/nerdctl/system_prune_linux_test.go
  cmd/nerdctl/volume_prune.go
  cmd/nerdctl/volume_prune_linux_test.go
  pkg/api/types/volume_types.go
  pkg/cmd/system/prune.go
  pkg/cmd/volume/prune.go
Labels: area/ci
