Repository containerd/nerdctl, pull requests merged in 2023-06, with the labels that each got.

#2267 Add Compose `shm_size` service option support
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#1644 Use docker compose v2 by default in `test-integration-docker-compatibility`
  cmd/nerdctl/compose_down_linux_test.go
  cmd/nerdctl/compose_kill_linux_test.go
  cmd/nerdctl/compose_restart_linux_test.go
  cmd/nerdctl/compose_run_linux_test.go
  cmd/nerdctl/compose_stop_linux_test.go
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/compose_version_test.go
  pkg/composer/logs.go
  pkg/composer/run.go
  pkg/composer/serviceparser/build_test.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
  pkg/testutil/testutil.go
Labels: area/compose, impact/major

#2287 docs: fixed typo in command ref for nerdctl logs follow
  docs/command-reference.md
Labels: documentation

#2326 Fix flaky test: test-integration-docker-compatibility: TestUniqueHostPortAssignement
  cmd/nerdctl/container_run_network_base_test.go
  cmd/nerdctl/container_run_network_linux_test.go
Labels: area/ci

#2318 Skip the BuildKit tests in the rootless integration
  .github/workflows/test.yml
  Dockerfile.d/test-integration-rootless.sh
  cmd/nerdctl/container_run_test.go
  cmd/nerdctl/image_encrypt_linux_test.go
  cmd/nerdctl/image_push_linux_test.go
Labels: area/ci

#2306 refactor: container stats command
  cmd/nerdctl/container_stats.go
  pkg/api/types/container_types.go
  pkg/cmd/container/stats.go
  pkg/cmd/container/stats_freebsd.go
  pkg/cmd/container/stats_linux.go
  pkg/cmd/container/stats_windows.go
Labels: kind/refactor

#2333 refactor: extract the printing logic out of pkg for container list
  cmd/nerdctl/container_list.go
  pkg/api/types/container_types.go
  pkg/cmd/container/list.go
  pkg/cmd/container/list_util.go
Labels: kind/refactor
