Repository containerd/nerdctl, pull requests merged in 2023-02, with the labels that each got.

#1934 refactor: container wait flagging process
  cmd/nerdctl/container_wait.go
  pkg/api/types/container_types.go
  pkg/cmd/container/wait.go
Labels: kind/refactor

#1983 Minor clean up for imgutil
  pkg/api/types/image_types.go
  pkg/api/types/pull_types.go
  pkg/cmd/image/list.go
  pkg/cmd/image/pull.go
  pkg/imgutil/filtering.go
  pkg/imgutil/imgutil.go
  pkg/ipfs/image.go
Labels: kind/refactor

#1971 Optimize id walkers and muti error handling
  cmd/nerdctl/container_stats.go
  cmd/nerdctl/container_update.go
  cmd/nerdctl/image_history.go
  pkg/cmd/container/inspect.go
  pkg/cmd/container/kill.go
  pkg/cmd/container/pause.go
  pkg/cmd/container/remove.go
  pkg/cmd/container/restart.go
  pkg/cmd/container/start.go
  pkg/cmd/container/stop.go
  pkg/cmd/container/unpause.go
  pkg/cmd/container/wait.go
  pkg/cmd/image/inspect.go
  pkg/cmd/image/remove.go
  pkg/cmd/image/save.go
  pkg/cmd/network/inspect.go
  pkg/cmd/network/remove.go
  pkg/idutil/containerwalker/containerwalker.go
  pkg/idutil/imagewalker/imagewalker.go
  pkg/idutil/netwalker/netwalker.go
Labels: kind/refactor

#1977 Split rootless driver tests by network driver and portdriver.
  .github/workflows/test.yml
Labels: area/rootless, area/ci

#1993 Fix the rename command on Windows
  cmd/nerdctl/container_rename_windows_test.go
  pkg/cmd/container/rename.go
Labels: platform/Windows/Non-WSL2

#2028 CI: test compilation with an old release of Go
  .github/workflows/test.yml
  Makefile
Labels: area/ci

#2030 Make confirm logic in `volume prune` be consistent with other Prune
  cmd/nerdctl/system_prune.go
  cmd/nerdctl/volume_prune.go
  pkg/api/types/volume_types.go
  pkg/cmd/volume/prune.go
Labels: kind/refactor

#1923 refactor: extract main logic of image.List
  cmd/nerdctl/image_list.go
  pkg/cmd/image/list.go
Labels: kind/refactor

#1930 refactor(container): refactor cp flag
  cmd/nerdctl/container_cp_linux.go
  pkg/api/types/container_types.go
  pkg/cmd/container/cp_linux.go
  pkg/containerutil/cp_linux.go
Labels: kind/refactor

#1985 [Refactor] refactor system prune flagging process
  cmd/nerdctl/system_prune.go
  pkg/api/types/builder_types.go
  pkg/api/types/system_types.go
  pkg/cmd/builder/prune.go
  pkg/cmd/system/prune.go
Labels: kind/refactor
