Repository containerd/nerdctl, pull requests merged in 2023-10, with the labels that each got.

#2567 nerdctl compose: fix `--env-file` (broken since v1.6.0)
  cmd/nerdctl/compose_config_test.go
  pkg/composer/composer.go
Labels: area/compose

#2586 docs: minor soci push fix
  docs/soci.md
Labels: documentation

#2579 [Chore] Replace logrus.SetOutput() with log.L.Logger.SetOutput()
  go.mod
  pkg/ocihook/ocihook.go
Labels: kind/refactor

#2606 Fix CI: `Vagrantfile.freebsd: pin generic/freebsd13 to version 4.3.2`; `compose_config_test: workaround for Docker Compose v2.23.0`
  Vagrantfile.freebsd
  cmd/nerdctl/compose_config_test.go
Labels: area/ci

#2589 Support run container with network id
  cmd/nerdctl/container_run_network_linux_test.go
  pkg/netutil/netutil.go
Labels: area/network
