Repository containerd/nerdctl, pull requests merged in 2023-12, with the labels that each got.

#2702 [doc] Fix deadlinks in the notation doc
  docs/notation.md
Labels: documentation

#2706 docs: Fix typo in command-reference.md
  docs/command-reference.md
Labels: documentation

#2711 Add `group-add` option in compose
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#2712 go.mod: clean up
  go.mod
Labels: easy-to-review

#2715 Remove "soci image rpull" from testing suite
  cmd/nerdctl/container_run_soci_linux_test.go
  cmd/nerdctl/image_pull_linux_test.go
Labels: area/ci

#2661 Allow for binding a named pipe on Windows
  cmd/nerdctl/container_run_mount_linux_test.go
  cmd/nerdctl/container_run_mount_windows_test.go
  go.mod
  go.sum
  pkg/cmd/container/create.go
  pkg/mountutil/mountutil.go
  pkg/mountutil/mountutil_freebsd.go
  pkg/mountutil/mountutil_linux.go
  pkg/mountutil/mountutil_linux_test.go
  pkg/mountutil/mountutil_other.go
  pkg/mountutil/mountutil_windows.go
  pkg/mountutil/mountutil_windows_test.go
  pkg/mountutil/mountutilmock/os.mock.go
  pkg/mountutil/mountutilmock/volumestore.mock.go
Labels: platform/Windows/Non-WSL2

#2720 Add docs for trouble shooting "nvidia gpu operator"
  docs/gpu.md
Labels: documentation
