Repository containerd/nerdctl, pull requests merged in 2023-07, with the labels that each got.

#2351 Update github.com/compose-spec/compose-go from 1.14.0 to 1.15.1 and fix testcase
  go.mod
  go.sum
  pkg/composer/serviceparser/build_test.go
Labels: area/compose

#2370 Deflake the Cirrus CI / Windows/containerd-1.7
  hack/configure-windows-ci.ps1
Labels: area/ci, platform/Windows/Non-WSL2

#2369 golangci-lint v1.53.3 and refactor linter rules
  .github/workflows/test.yml
  .golangci.yml
Labels: area/ci

#2387 CI: test-integration-docker-compatibility: enable BuildKit
  .github/workflows/test.yml
  cmd/nerdctl/builder_build_test.go
  cmd/nerdctl/image_list_test.go
Labels: area/ci

#2371 Refactor codebase and re-enable `revive` linter rules
  .golangci.yml
  cmd/nerdctl/builder_build.go
  cmd/nerdctl/container_update.go
  pkg/cmd/container/create.go
  pkg/cmd/container/run_gpus.go
  pkg/cmd/container/top.go
  pkg/composer/config.go
  pkg/composer/create.go
  pkg/composer/pipetagger/pipetagger.go
  pkg/composer/restart.go
  pkg/composer/run.go
  pkg/composer/up.go
  pkg/composer/up_service.go
  pkg/dnsutil/hostsstore/updater.go
  pkg/imgutil/jobs/jobs.go
  pkg/logging/cri_logger_test.go
  pkg/mountutil/volumestore/volumestore.go
  pkg/netutil/netutil.go
  pkg/ocihook/ocihook.go
  pkg/signutil/cosignutil.go
  pkg/signutil/notationutil.go
Labels: kind/refactor

#2399 registry documentation update
  docs/registry.md
Labels: documentation, area/login
