Repository containerd/nerdctl, pull requests merged in 2024-11, with the labels that each got.

#3608 Rewrite container_wait tests
  cmd/nerdctl/container/container_wait_test.go
Labels: area/ci

#3619 Cleanup container_create tests
  cmd/nerdctl/container/container_create_linux_test.go
  cmd/nerdctl/container/container_create_test.go
  cmd/nerdctl/container/container_create_windows_test.go
Labels: area/ci

#3611 Rewrite container prune test
  cmd/nerdctl/container/container_prune_linux_test.go
Labels: area/ci

#3610 Rewrite container remove test
  cmd/nerdctl/container/container_remove_test.go
Labels: area/ci

#3615 Rewrite container_stats tests
  cmd/nerdctl/container/container_stats_linux_test.go
  cmd/nerdctl/container/container_stats_test.go
Labels: area/ci

#3630 Cosmetic tests
  cmd/nerdctl/completion/completion_test.go
  cmd/nerdctl/container/container_commit_linux_test.go
  cmd/nerdctl/container/container_commit_test.go
  cmd/nerdctl/container/container_remove_test.go
  cmd/nerdctl/image/image_load_test.go
  cmd/nerdctl/image/image_prune_test.go
  cmd/nerdctl/issues/issues_linux_test.go
  cmd/nerdctl/network/network_create_linux_test.go
  cmd/nerdctl/network/network_inspect_test.go
  cmd/nerdctl/network/network_prune_linux_test.go
  cmd/nerdctl/network/network_remove_linux_test.go
Labels: area/ci

#3583 GHA cache image build dependencies
  .github/workflows/test.yml
  Dockerfile
Labels: area/ci

#3632 Alpine > Common
  cmd/nerdctl/container/container_commit_linux_test.go
  cmd/nerdctl/container/container_commit_test.go
  cmd/nerdctl/container/container_create_linux_test.go
  cmd/nerdctl/container/container_exec_linux_test.go
  cmd/nerdctl/container/container_list_test.go
  cmd/nerdctl/container/container_prune_linux_test.go
  cmd/nerdctl/container/container_remove_test.go
  cmd/nerdctl/container/container_rename_linux_test.go
  cmd/nerdctl/container/container_rename_windows_test.go
  cmd/nerdctl/container/container_restart_linux_test.go
  cmd/nerdctl/container/container_run_cgroup_linux_test.go
  cmd/nerdctl/container/container_run_linux_test.go
  cmd/nerdctl/container/container_run_mount_linux_test.go
  cmd/nerdctl/container/container_run_network_linux_test.go
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/container/container_stats_test.go
  cmd/nerdctl/container/container_top_test.go
  cmd/nerdctl/image/image_remove_test.go
  cmd/nerdctl/ipfs/ipfs_kubo_linux_test.go
  cmd/nerdctl/ipfs/ipfs_registry_linux_test.go
  cmd/nerdctl/ipfs/ipfs_simple_linux_test.go
  cmd/nerdctl/issues/main_linux_test.go
  cmd/nerdctl/network/network_create_linux_test.go
  cmd/nerdctl/network/network_prune_linux_test.go
  cmd/nerdctl/network/network_remove_linux_test.go
  pkg/testutil/nerdtest/utilities.go
Labels: area/ci

#3633 add 'none' logger
  pkg/logging/log_viewer.go
  pkg/logging/logging.go
  pkg/logging/none_logger.go
  pkg/logging/none_logger_test.go
Labels: area/logging

#3614 fix: not to be deleted a container created with --rm when detaching
  cmd/nerdctl/container/container_attach_linux_test.go
  cmd/nerdctl/container/container_run.go
  cmd/nerdctl/container/container_run_linux_test.go
  pkg/cmd/container/attach.go
  pkg/cmd/container/create.go
  pkg/containerutil/containerutil.go
  pkg/labels/labels.go
Labels: area/ci

#3655 Mark `nerdctl builder debug` as incompatible with Docker
  cmd/nerdctl/builder/builder_builder_test.go
  docs/command-reference.md
Labels: area/ci

#3640 feat: adds IP address configuration for default bridge network
  cmd/nerdctl/helpers/flagutil.go
  cmd/nerdctl/internal/internal_oci_hook.go
  cmd/nerdctl/main.go
  docs/config.md
  pkg/cmd/compose/compose.go
  pkg/cmd/container/kill.go
  pkg/config/config.go
  pkg/containerutil/container_network_manager_linux.go
  pkg/containerutil/container_network_manager_windows.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_linux_test.go
  pkg/netutil/netutil_test.go
  pkg/ocihook/ocihook.go
Labels: area/network

#3666 refactor: Fix golanglint action error
  cmd/nerdctl/container/container_diff.go
  pkg/imgutil/filtering.go
Labels: area/ci, kind/refactor

#3665 refactor: Use a more direct and less error-prone return value
  pkg/netutil/subnet/subnet.go
Labels: kind/refactor

#3670 fix: default json-file log size to 100MB
  pkg/logging/json_logger.go
Labels: cherry-pick/1.7

#3683 Pass appropriate --device arguments from compose to run
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
Labels: area/compose

#3667 add fields such as CONTAINER_NAME to journald log entries sent to by containers
  cmd/nerdctl/container/container_run_test.go
  pkg/cmd/container/create.go
  pkg/cmd/system/info.go
  pkg/infoutil/infoutil.go
  pkg/logging/fluentd_logger.go
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/logging.go
  pkg/logging/logging_test.go
  pkg/logging/none_logger.go
  pkg/logging/none_logger_test.go
  pkg/logging/syslog_logger.go
Labels: enhancement, area/logging
