Repository containerd/nerdctl, pull requests merged in 2024-02, with the labels that each got.

#2786 Support `nerdctl build` args: `--attest`,` --sbom`,`--provenance`
  cmd/nerdctl/builder_build.go
  cmd/nerdctl/builder_build_test.go
  docs/command-reference.md
  pkg/api/types/builder_types.go
  pkg/cmd/builder/build.go
Labels: kind/external/buildkit

#2785 Support systemd in containers with podman-style `--systemd` flag
  README.md
  cmd/nerdctl/container_create.go
  cmd/nerdctl/container_run.go
  cmd/nerdctl/container_run_systemd_linux_test.go
  docs/command-reference.md
  pkg/api/types/container_types.go
  pkg/cmd/container/create.go
  pkg/testutil/testutil_linux.go
Labels: enhancement

#2798 update RootlessKit (2.0.1)
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.0
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.1
Labels: cherry-pick/1.7

#2800 [release/1.7] update RootlessKit (2.0.1)
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.0
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.1
Labels: area/rootless

#2819 [cherry-picked to v1.7.4] rootless: fix `Not Authorized(uid): org.fedoraproject.FirewallD1.config`
  pkg/netutil/cni_plugin_unix.go
Labels: area/rootless, priority/high, cherry-pick/1.7, cherry-pick/done

#2822 [release/1.7] rootless: fix `Not Authorized(uid): org.fedoraproject.FirewallD1.config`
  pkg/netutil/cni_plugin_unix.go
Labels: area/rootless, priority/high

#2829 [cherry-picked to v1.7.4] CI: test compilation with Go 1.22
  .github/workflows/test.yml
Labels: cherry-pick/1.7, cherry-pick/done

#2832 Rootlesskit Network Design
  docs/images/rootlessKit-network-design.png
  docs/rootless.md
Labels: documentation, area/rootless
