Repository containerd/nerdctl, pull requests merged in 2024-05, with the labels that each got.

#2967 CI: use Go 1.22
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
Labels: area/ci, cherry-pick/1.7

#2823 doc: should use master tag for binfmt
  docs/multi-platform.md
Labels: documentation

#2979 Fix markdown link
  docs/rootless.md
Labels: documentation

#3024 ci: Add retry on github action
  .github/workflows/test.yml
Labels: area/ci

#3031 Do not obtain task info when it is not necessary in commit command
  pkg/imgutil/commit/commit.go
Labels: kind/refactor
