Repository containerd/nerdctl, pull requests merged in 2024-07, with the labels that each got.

#3170 Cleanup login command (remove global var and normalize to other commands
  cmd/nerdctl/login.go
Labels: kind/refactor, area/login

#3172 Separate and expand information on testing for newcomers
  README.md
  docs/testing.md
Labels: documentation, area/ci

#3180 Re-enable project checks for .md only changes
  .github/workflows/project.yml
  .github/workflows/test.yml
Labels: area/ci

#3179 Workaround flaky save
  cmd/nerdctl/container_run_linux_test.go
  cmd/nerdctl/image_save_linux_test.go
  cmd/nerdctl/image_save_test.go
Labels: area/ci

#3174 Add logo
  README.md
  docs/images/nerdctl.svg
Labels: documentation, area/project

#3188 [PRIORITY] Improve tests debugging output
  cmd/nerdctl/container_create_linux_test.go
  cmd/nerdctl/container_run_linux_test.go
  cmd/nerdctl/container_run_network_linux_test.go
  cmd/nerdctl/container_run_security_linux_test.go
  cmd/nerdctl/container_run_test.go
  cmd/nerdctl/image_push_linux_test.go
  pkg/testutil/testutil.go
Labels: area/ci

#3184 Dependabot: add groups
  .github/dependabot.yml
Labels: area/ci

#3182 test-integration-rootless: enable BuildKit for RootlessKit v2
  .github/workflows/test.yml
  cmd/nerdctl/builder_linux_test.go
Labels: area/rootless, area/ci

#3178 Move to 24.04 for docker tests
  .github/workflows/test.yml
  cmd/nerdctl/container_logs_test.go
  cmd/nerdctl/container_run_cgroup_linux_test.go
Labels: area/ci

#3198 CI test fix: wait for systemd to come up
  cmd/nerdctl/container_run_systemd_linux_test.go
Labels: area/ci

#3201 rootless: add `Requires=dbus.socket`
  extras/rootless/containerd-rootless-setuptool.sh
Labels: area/rootless

#3181 Fix IPFS container start routine
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  pkg/testutil/testregistry/testregistry_linux.go
Labels: area/ci, area/ipfs

#3206 CI: shrink test matrix
  .github/workflows/test.yml
Labels: area/ci

#3207 Test fixes
  cmd/nerdctl/builder_build_test.go
  cmd/nerdctl/container_logs_test.go
  pkg/testutil/testutil_linux.go
Labels: area/ci

#3158 Fix nerdctl info on Windows
  pkg/cmd/system/info.go
  pkg/infoutil/infoutil_unix.go
  pkg/infoutil/infoutil_windows.go
  pkg/infoutil/infoutil_windows_test.go
  pkg/infoutil/infoutilmock/info.util.mock.go
Labels: platform/Windows/Non-WSL2

#3166 Add repository login component username validation
  cmd/nerdctl/login.go
Labels: area/login

#3224 [PRIORITY] Account for availability delay of golang docker image
  hack/build-integration-canary.sh
Labels: area/ci

#3263 gracefully terminate containers on nerdctl compose down
  pkg/composer/down.go
Labels: area/compose
