Repository containerd/nerdctl, pull requests merged in 2024-01, with the labels that each got.

#2725 cniNetworkManager: move Windows-specific variable to `_windows.go`
  pkg/containerutil/container_network_manager.go
  pkg/containerutil/container_network_manager_linux.go
  pkg/containerutil/container_network_manager_other.go
  pkg/containerutil/container_network_manager_windows.go
Labels: kind/refactor

#2727 logging: respect ctx
  .github/workflows/test.yml
  Dockerfile
  cmd/nerdctl/container_run_test.go
  go.mod
  go.sum
  pkg/logging/logging.go
Labels: priority/high

#2750 Document that profiles are supported
  docs/compose.md
Labels: documentation, area/compose

#2762 CI: use standard GHA runners
  .github/workflows/test.yml
Labels: area/ci

#2763 CI: use standard GHA runner for Windows too
  .github/workflows/test.yml
Labels: area/ci, platform/Windows/Non-WSL2

#2723 [Carry 2535] rootless: support detach-netns mode
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/buildkit-v0.12.4
  Dockerfile.d/SHA256SUMS.d/buildkit-v0.13.0-beta2
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.0
  README.md
  cmd/nerdctl/container_run_network_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  docs/rootless.md
  extras/rootless/containerd-rootless-setuptool.sh
  extras/rootless/containerd-rootless.sh
  pkg/cmd/container/create.go
  pkg/containerutil/container_network_manager.go
  pkg/defaults/defaults_linux.go
  pkg/netutil/netutil_unix.go
  pkg/netutil/subnet/subnet.go
  pkg/rootlessutil/parent_linux.go
  pkg/rootlessutil/rootlessutil_linux.go
  pkg/rootlessutil/rootlessutil_other.go
  pkg/testutil/nettestutil/nettestutil.go
Labels: area/rootless, impact/major

#2778 update containerd (1.7.13), runc (1.1.12), bypass4netns (0.4.0), Kubo (0.26.0)
  .github/workflows/test.yml
  Dockerfile
Labels: cherry-pick/1.7, cherry-pick/done
