Repository containerd/nerdctl, pull requests merged in 2024-06, with the labels that each got.

#3042 Disabling test on unsupported platforms
  cmd/nerdctl/container_run_stargz_linux_test.go
Labels: area/ci

#3041 CI: .md files changes should not trigger tests
  .github/workflows/test.yml
Labels: area/ci

#3040 State how to run a single integration test
  README.md
Labels: documentation

#3067 MAINTAINERS: move Hanchin Hsieh (yuchanns) from a REVIEWER to a EMERITUS
  EMERITUS.md
  MAINTAINERS
Labels: area/project

#3089 test-integration-docker-compatibility: install Docker v24
  .github/workflows/test.yml
Labels: area/ci

#3065 MAINTAINERS: promote Jin Dong (djdongjin) from a REVIEWER to a COMMITTER
  MAINTAINERS
Labels: area/project

#3064 MAINTAINERS: promote Kay Yan (yankay) from a REVIEWER to a COMMITTER
  MAINTAINERS
Labels: area/project

#3107 Disable build and publish on PR for purely md changes
  .github/workflows/ghcr-image-build-and-publish.yml
Labels: area/ci

#3106 Add doc note about --ip and bridge
  docs/command-reference.md
Labels: documentation, area/network

#3097 Docker v26 compatibility & test fixes
  .github/workflows/test.yml
  cmd/nerdctl/container_create_linux_test.go
  cmd/nerdctl/container_run_network_linux_test.go
  cmd/nerdctl/network_inspect_test.go
  pkg/containerutil/container_network_manager.go
Labels: area/ci

#3105 Add mechanism to prevent Cmd from executing multiple times
  pkg/testutil/testutil.go
Labels: area/ci

#3111 Replace SetEnv invocation by base.Env to unlock parallelization
  cmd/nerdctl/builder_build_test.go
  cmd/nerdctl/compose_config_test.go
  cmd/nerdctl/compose_exec_linux_test.go
  cmd/nerdctl/compose_run_linux_test.go
  cmd/nerdctl/compose_up_linux_test.go
  cmd/nerdctl/container_exec_test.go
  cmd/nerdctl/container_run_test.go
  cmd/nerdctl/container_run_verify_linux_test.go
  cmd/nerdctl/image_pull_linux_test.go
  cmd/nerdctl/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs_linux_test.go
  cmd/nerdctl/ipfs_registry_linux_test.go
  cmd/nerdctl/main_test.go
  cmd/nerdctl/system_info_test.go
  pkg/testutil/testutil.go
Labels: area/ci, area/cosign

#3112 MAINTAINERS: move Ye Sijun (junnplus) from a COMMITTER to a EMERITUS
  EMERITUS.md
  MAINTAINERS
Labels: area/project

#3096 [Proposal] Implement namespacing for networks
  cmd/nerdctl/completion.go
  cmd/nerdctl/network_inspect_test.go
  cmd/nerdctl/network_remove_linux_test.go
  docs/cni.md
  docs/dir.md
  pkg/cmd/compose/compose.go
  pkg/cmd/container/kill.go
  pkg/cmd/network/create.go
  pkg/cmd/network/inspect.go
  pkg/cmd/network/list.go
  pkg/cmd/network/prune.go
  pkg/cmd/network/remove.go
  pkg/containerutil/container_network_manager_linux.go
  pkg/containerutil/container_network_manager_windows.go
  pkg/netutil/netutil.go
  pkg/ocihook/ocihook.go
Labels: impact/major, area/network

#3116 Aftermath docker migration: fix racyness in tests
  cmd/nerdctl/container_create_linux_test.go
Labels: area/ci

#3122 Remove duplicate function
  cmd/nerdctl/completion_linux_test.go
  cmd/nerdctl/compose_pull_linux_test.go
  cmd/nerdctl/container_logs_test.go
  cmd/nerdctl/image_prune_test.go
  cmd/nerdctl/image_remove_linux_test.go
  cmd/nerdctl/network_create_linux_test.go
  cmd/nerdctl/network_prune_linux_test.go
  cmd/nerdctl/system_prune_linux_test.go
  cmd/nerdctl/volume_prune_linux_test.go
  pkg/testutil/testutil.go
Labels: area/ci, kind/refactor

#3117 Bump compose-go to v2
  .golangci.yml
  cmd/nerdctl/compose_up.go
  go.mod
  go.sum
  pkg/composer/build.go
  pkg/composer/composer.go
  pkg/composer/config.go
  pkg/composer/create.go
  pkg/composer/down.go
  pkg/composer/logs.go
  pkg/composer/projectloader/projectloader.go
  pkg/composer/pull.go
  pkg/composer/push.go
  pkg/composer/restart.go
  pkg/composer/run.go
  pkg/composer/serviceparser/build.go
  pkg/composer/serviceparser/serviceparser.go
  pkg/composer/serviceparser/serviceparser_test.go
  pkg/composer/up.go
  pkg/composer/up_network.go
  pkg/composer/up_volume.go
Labels: area/compose

#3128 update golangci-lint (1.59.1)
  .github/workflows/test.yml
  cmd/nerdctl/image_inspect_test.go
  pkg/cmd/container/stats.go
Labels: area/ci

#3129 CI: update Ubuntu (24.04)
  .github/workflows/ghcr-image-build-and-publish.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/test-integration-rootless.sh
  pkg/testutil/testutil.go
Labels: area/ci
