Repository containerd/nerdctl, pull requests merged in 2024-03, with the labels that each got.

#2849 fix: typos
  docs/ipfs.md
Labels: documentation

#2855 chore: remove useless error check
  cmd/nerdctl/main_unix.go
  cmd/nerdctl/network_create.go
Labels: kind/refactor

#2871 CI: update FreeBSD to 14
  Vagrantfile.freebsd
Labels: area/ci, platform/FreeBSD

#2878 update CNI plugins (1.4.1), RootlessKit (2.0.2), Kubo (0.27.0)
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/cni-plugins-v1.4.0
  Dockerfile.d/SHA256SUMS.d/cni-plugins-v1.4.1
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.1
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.0.2
Labels: cherry-pick/1.7

#2873 feat(compose_up): add --abort-on-container-exit flag
  cmd/nerdctl/compose_up.go
  cmd/nerdctl/compose_up_linux_test.go
  docs/command-reference.md
  pkg/composer/logs.go
  pkg/composer/up.go
  pkg/composer/up_service.go
Labels: area/compose

#2896 update cosign image to latest release
  Dockerfile
Labels: documentation, area/ci, area/cosign, cherry-pick/1.7

#2897 Deflake IPFS and EStargz tests
  cmd/nerdctl/image_convert_test.go
  cmd/nerdctl/ipfs_linux_test.go
Labels: area/ci

#2898 CI: FreeBSD: use Go 1.22
  Vagrantfile.freebsd
Labels: area/ci, platform/FreeBSD
