Repository containerd/nerdctl, pull requests merged in 2024-10, with the labels that each got.

#3484 Fix login persistence regression against Hub
  pkg/imgutil/dockerconfigresolver/credentialsstore.go
  pkg/imgutil/dockerconfigresolver/credentialsstore_test.go
  pkg/imgutil/dockerconfigresolver/registryurl_test.go
Labels: area/login

#3490 Fix IPFS missing layer issue
  cmd/nerdctl/issues/issues_linux_test.go
  pkg/cmd/image/ensure.go
  pkg/cmd/image/push.go
  pkg/ipfs/image.go
Labels: area/ipfs

#3464 Test rework, part 3
  cmd/nerdctl/container/container_create_linux_test.go
  cmd/nerdctl/network/network_prune_linux_test.go
  cmd/nerdctl/system/system_prune_linux_test.go
  cmd/nerdctl/volume/volume_prune_linux_test.go
  docs/testing/tools.md
  pkg/testutil/nerdtest/helpers.go
  pkg/testutil/nerdtest/requirements.go
  pkg/testutil/nerdtest/test.go
  pkg/testutil/test/case.go
  pkg/testutil/test/command.go
  pkg/testutil/test/data.go
  pkg/testutil/test/requirement.go
  pkg/testutil/test/test.go
  pkg/testutil/testutil_linux.go
Labels: area/ci

#3499 Remove images from Docker Hub from tests
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/image/image_list_test.go
  pkg/testutil/testutil_linux.go
  pkg/testutil/testutil_windows.go
Labels: area/ci

#3532 Remove `ipfs` binary from `nerdctl-full`
  Dockerfile
Labels: impact/major, area/ipfs

#3541 Skip TestRunWithTtyAndDetached on Windows
  cmd/nerdctl/container/container_run_windows_test.go
Labels: area/ci, platform/Windows/Non-WSL2

#3548 Lint fixes
  pkg/mountutil/mountutil_test.go
  pkg/netutil/netutil.go
  pkg/testutil/testutil_freebsd.go
Labels: area/ci

#3547 Consistently enforce rmi -f in tests cleanup
  cmd/nerdctl/image/image_convert_linux_test.go
  cmd/nerdctl/image/image_list_test.go
  cmd/nerdctl/image/image_load_test.go
  cmd/nerdctl/image/image_prune_test.go
  cmd/nerdctl/image/image_pull_linux_test.go
  cmd/nerdctl/image/image_push_linux_test.go
  cmd/nerdctl/ipfs/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs/ipfs_kubo_linux_test.go
  cmd/nerdctl/ipfs/ipfs_registry_linux_test.go
  cmd/nerdctl/ipfs/ipfs_simple_linux_test.go
Labels: area/ci

#3559 Skip TestAttach until we fix it
  cmd/nerdctl/container/container_attach_linux_test.go
Labels: area/ci

#3561 Add pseudo tty support for tests
  cmd/nerdctl/issues/main_linux_test.go
  pkg/testutil/test/command.go
  pkg/testutil/test/pty.go
  pkg/testutil/test/pty_freebsd.go
  pkg/testutil/test/pty_linux.go
  pkg/testutil/test/pty_windows.go
  pkg/testutil/test/test.go
Labels: area/ci

#3543 Global compose lock
  pkg/cmd/compose/compose.go
Labels: area/compose

#3550 Part 5: tests
  cmd/nerdctl/container/container_commit_linux_test.go
  cmd/nerdctl/container/container_commit_test.go
  cmd/nerdctl/issues/issues_linux_test.go
  cmd/nerdctl/login/login_linux_test.go
  pkg/testutil/nerdtest/requirements.go
  pkg/testutil/nerdtest/third-party.go
  pkg/testutil/testregistry/testregistry_linux.go
  pkg/testutil/testutil.go
Labels: area/ci

#3574 Workaround and document weird docker issue
  cmd/nerdctl/container/container_commit_test.go
Labels: area/ci

#3575 Separate lint + enable on other platforms
  .github/workflows/lint.yml
  .github/workflows/test-canary.yml
  .github/workflows/test.yml
Labels: area/ci

#3573 Fix ensurecontainerstarted logic and better debug
  docs/testing/tools.md
  pkg/testutil/nerdtest/registry/cesanta.go
  pkg/testutil/nerdtest/utilities.go
  pkg/testutil/test/command.go
  pkg/testutil/test/helpers.go
Labels: area/ci

#3572 Enhance debugability for kubernetes rig
  hack/build-integration-kubernetes.sh
Labels: area/ci

#3535 CI adjustments
  .github/workflows/ghcr-image-build-and-publish.yml
  .github/workflows/lint.yml
  .github/workflows/project.yml
  .github/workflows/test-canary.yml
  .github/workflows/test-kube.yml
  .github/workflows/test.yml
  Dockerfile
  Makefile
  hack/test-integration.sh
  pkg/testutil/testutil.go
Labels: area/ci

#3599 Add logo for the dark mode in readme.md
  README.md
  docs/images/nerdctl-white.svg
Labels: documentation

#3617 Update busybox image (support sleep inf)
  cmd/nerdctl/builder/builder_builder_test.go
  pkg/testutil/testutil_freebsd.go
  pkg/testutil/testutil_linux.go
  pkg/testutil/testutil_windows.go
Labels: area/ci

#3618 Fix test leaking tagged Alpine image
  cmd/nerdctl/builder/builder_builder_test.go
Labels: area/ci
