Repository containerd/nerdctl, pull requests merged in 2024-09, with the labels that each got.

#3293 Login & authentication rework, part 1: credentials management and URL parsing
  cmd/nerdctl/login/login_linux_test.go
  cmd/nerdctl/login/logout.go
  pkg/cmd/login/login.go
  pkg/cmd/logout/logout.go
  pkg/imgutil/dockerconfigresolver/credentialsstore.go
  pkg/imgutil/dockerconfigresolver/credentialsstore_test.go
  pkg/imgutil/dockerconfigresolver/defaults.go
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go
  pkg/imgutil/dockerconfigresolver/dockerconfigresolver_util.go
  pkg/imgutil/dockerconfigresolver/registryurl.go
  pkg/imgutil/dockerconfigresolver/registryurl_test.go
  pkg/testutil/testregistry/testregistry_linux.go
  pkg/testutil/testutil.go
Labels: area/login

#3407 Lint for other platforms
  Makefile
  cmd/nerdctl/container/container_cp.go
  cmd/nerdctl/container/container_cp_linux.go
  cmd/nerdctl/container/container_list_windows_test.go
  cmd/nerdctl/container/container_run_network_base_test.go
  cmd/nerdctl/container/container_run_network_linux_test.go
  cmd/nerdctl/container/container_run_network_windows_test.go
  cmd/nerdctl/image/image_encrypt_linux_test.go
  pkg/cmd/container/run_cgroup_freebsd.go
  pkg/cmd/container/run_cgroup_windows.go
  pkg/cmd/container/run_gpus.go
  pkg/cmd/container/run_linux.go
  pkg/cmd/container/run_ulimit_linux.go
  pkg/cmd/container/run_windows.go
  pkg/cmd/container/top.go
  pkg/cmd/container/top_unix.go
  pkg/containerutil/container_network_manager.go
  pkg/containerutil/container_network_manager_windows.go
  pkg/netutil/netutil_test.go
  pkg/netutil/netutil_windows.go
  pkg/ocihook/ocihook_freebsd.go
  pkg/ocihook/ocihook_windows.go
  pkg/statsutil/stats.go
  pkg/statsutil/stats_linux.go
  pkg/sysinfo/sysinfo.go
  pkg/testutil/iptables/iptables_linux.go
  pkg/testutil/testregistry/certsd_linux.go
  pkg/testutil/testutil_freebsd.go
Labels: area/ci

#3402 CI/test fixing
  cmd/nerdctl/container/container_run_security_linux_test.go
  cmd/nerdctl/image/image_load_linux_test.go
Labels: area/ci

#3392 Login & authentication rework, part 2: prompt cleanup
  pkg/cmd/login/login.go
  pkg/cmd/login/prompt.go
  pkg/cmd/login/prompt_unix.go
  pkg/cmd/login/prompt_windows.go
Labels: area/login

#3405 Draft design document for store
  .github/workflows/test-canary.yml
  .github/workflows/test-kube.yml
  .github/workflows/test.yml
  README.md
  docs/dev/store.md
  docs/dev/testing.md
Labels: documentation

#3304 Remove leading slash in Windows path
  cmd/nerdctl/container/container_run_linux_test.go
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/container/container_run_windows_test.go
  pkg/taskutil/taskutil.go
Labels: platform/Windows/Non-WSL2

#3418 New test tooling
  .github/workflows/test-canary.yml
  .github/workflows/test-kube.yml
  .github/workflows/test.yml
  README.md
  cmd/nerdctl/main_linux_test.go
  cmd/nerdctl/main_test.go
  cmd/nerdctl/main_test_test.go
  cmd/nerdctl/volume/volume_create_test.go
  cmd/nerdctl/volume/volume_inspect_test.go
  cmd/nerdctl/volume/volume_list_test.go
  cmd/nerdctl/volume/volume_namespace_test.go
  cmd/nerdctl/volume/volume_prune_linux_test.go
  cmd/nerdctl/volume/volume_remove_linux_test.go
  docs/testing/README.md
  docs/testing/tools.md
  pkg/testutil/nerdtest/test.go
  pkg/testutil/test/case.go
  pkg/testutil/test/command.go
  pkg/testutil/test/data.go
  pkg/testutil/test/expected.go
  pkg/testutil/test/helpers.go
  pkg/testutil/test/requirement.go
  pkg/testutil/test/test.go
Labels: area/ci
