Repository containerd/nerdctl, pull requests merged in 2025-05, with the labels that each got.

#3896 fix: logs updated on starting of a stopped container
  cmd/nerdctl/compose/compose_start.go
  cmd/nerdctl/container/container_logs_test.go
  cmd/nerdctl/container/container_start.go
  cmd/nerdctl/container/container_start_linux_test.go
  pkg/api/types/container_types.go
  pkg/cmd/container/restart.go
  pkg/cmd/container/start.go
  pkg/containerutil/containerutil.go
  pkg/errutil/exit_coder.go
  pkg/taskutil/taskutil.go
Labels: area/logging

#3941 feat: add support for userns
  .github/workflows/job-test-in-container.yml
  .golangci.yml
  cmd/nerdctl/builder/builder_build.go
  cmd/nerdctl/container/container_create.go
  cmd/nerdctl/container/container_create_linux_test.go
  cmd/nerdctl/container/container_run.go
  cmd/nerdctl/container/container_run_user_linux_test.go
  cmd/nerdctl/main.go
  docs/command-reference.md
  docs/config.md
  go.mod
  pkg/api/types/container_types.go
  pkg/cmd/container/create.go
  pkg/cmd/container/create_userns_opts_darwin.go
  pkg/cmd/container/create_userns_opts_freebsd.go
  pkg/cmd/container/create_userns_opts_linux.go
  pkg/cmd/container/create_userns_opts_linux_test.go
  pkg/cmd/container/create_userns_opts_windows.go
  pkg/cmd/container/idmap.go
  pkg/config/config.go
  pkg/testutil/nerdtest/requirements.go
  pkg/testutil/testutil.go
Labels: impact/major, kind/feature

#4216 TestRunWithLogBinary: workaround for "package slices is not in GOROOT"
  cmd/nerdctl/container/container_run_test.go
Labels: priority/high, area/ci

#4226 fix: remove trailing newline from log entries on last decode iteration
  cmd/nerdctl/container/container_logs_test.go
  pkg/logging/json_logger_test.go
  pkg/logging/jsonfile/jsonfile.go
  pkg/logging/logging.go
Labels: area/logging

#4242 Dockerfile: fix cross-compiling gomodjail
  .github/workflows/ghcr-image-build-and-publish.yml
  .github/workflows/release.yml
  Dockerfile
Labels: priority/high, area/ci

#4228 MAINTAINERS: add Shubharanshu Mahapatra (Shubhranshu153) as a REVIEWER
  MAINTAINERS
Labels: area/project

#4258 Add support for compose AdditionalContexts
  pkg/composer/serviceparser/build.go
Labels: area/compose
