Repository containerd/nerdctl, pull requests merged in 2025-01, with the labels that each got.

#3744 Fix duplicate image entries in k8s.io namespaces
  cmd/nerdctl/helpers/flagutil.go
  cmd/nerdctl/image/image_list_test.go
  cmd/nerdctl/image/image_remove_test.go
  cmd/nerdctl/main.go
  docs/config.md
  pkg/cmd/image/list.go
  pkg/cmd/image/remove.go
  pkg/config/config.go
  pkg/idutil/imagewalker/imagewalker.go
Labels: area/kubernetes

#3824 Correct `compose logs` command reference
  docs/command-reference.md
Labels: documentation

#3828 [Carry 3827] update Kubo (0.32.1)
  Dockerfile
  Dockerfile.d/test-integration-ipfs-offline.service
Labels: area/ipfs

#3827 update Kubo (0.32.1)
  Dockerfile
Labels: area/ci, area/ipfs
