Repository containerd/nerdctl, pull requests merged in 2025-04, with the labels that each got.

#4058 [P0] [CI] Adjust drifting test
  cmd/nerdctl/image/image_history_test.go
Labels: area/ci

#4056 [CI] new command implementation for tests
  Vagrantfile.freebsd
  cmd/nerdctl/builder/builder_build_test.go
  cmd/nerdctl/builder/builder_builder_test.go
  cmd/nerdctl/container/container_attach_linux_test.go
  cmd/nerdctl/container/container_run_linux_test.go
  cmd/nerdctl/container/container_start_linux_test.go
  cmd/nerdctl/image/image_list_test.go
  cmd/nerdctl/image/image_load_test.go
  cmd/nerdctl/ipfs/ipfs_compose_linux_test.go
  cmd/nerdctl/ipfs/ipfs_registry_linux_test.go
  cmd/nerdctl/issues/main_linux_test.go
  cmd/nerdctl/main_test_test.go
  cmd/nerdctl/system/system_events_linux_test.go
  cmd/nerdctl/volume/volume_create_test.go
  mod/tigron/.golangci.yml
  mod/tigron/expect/comparators.go
  mod/tigron/expect/exit.go
  mod/tigron/go.mod
  mod/tigron/go.sum
  mod/tigron/internal/com/command.go
  mod/tigron/internal/com/command_other.go
  mod/tigron/internal/com/command_test.go
  mod/tigron/internal/com/command_windows.go
  mod/tigron/internal/com/doc.go
  mod/tigron/internal/com/package_benchmark_test.go
  mod/tigron/internal/com/package_example_test.go
  mod/tigron/internal/com/package_test.go
  mod/tigron/internal/com/pipes.go
  mod/tigron/internal/exit.go
  mod/tigron/internal/highk/fileleak.go
  mod/tigron/internal/logger/doc.go
  mod/tigron/internal/logger/logger.go
  mod/tigron/internal/pty/pty.go
  mod/tigron/test/case.go
  mod/tigron/test/command.go
  mod/tigron/test/helpers.go
  mod/tigron/test/interfaces.go
  mod/tigron/test/package_test.go
  pkg/testutil/nerdtest/command.go
  pkg/testutil/nerdtest/utilities_linux.go
Labels: area/ci

#4096 CI: FreeBSD: fix "No packages available to install matching ..."
  Vagrantfile.freebsd
Labels: area/ci, platform/FreeBSD

#4076 [Tigron]: mocks + debugging output enhancements
  mod/tigron/.golangci.yml
  mod/tigron/expect/comparators.go
  mod/tigron/internal/assertive/assertive.go
  mod/tigron/internal/assertive/assertive_test.go
  mod/tigron/internal/com/command_test.go
  mod/tigron/internal/formatter/doc.go
  mod/tigron/internal/formatter/formatter.go
  mod/tigron/internal/formatter/osc8.go
  mod/tigron/internal/mimicry/doc.go
  mod/tigron/internal/mimicry/doc.md
  mod/tigron/internal/mimicry/mimicry.go
  mod/tigron/internal/mimicry/print.go
  mod/tigron/internal/mimicry/stack.go
  mod/tigron/internal/mocks/doc.go
  mod/tigron/internal/mocks/t.go
  mod/tigron/test/command.go
  mod/tigron/test/data_test.go
  mod/tigron/tig/doc.go
  mod/tigron/tig/t.go
Labels: area/ci

#4079 [Tigron]: expect.JSON comparator and updated volume test
  cmd/nerdctl/volume/volume_inspect_test.go
  mod/tigron/expect/comparators.go
  mod/tigron/expect/comparators_test.go
  mod/tigron/expect/doc.md
  mod/tigron/internal/com/command_test.go
Labels: area/ci

#4080 [Tigron]: Testing logs user experience
  mod/tigron/.golangci.yml
  mod/tigron/expect/comparators.go
  mod/tigron/go.mod
  mod/tigron/go.sum
  mod/tigron/internal/assertive/assertive.go
  mod/tigron/internal/formatter/formatter.go
  mod/tigron/internal/mimicry/print.go
  mod/tigron/test/case.go
  mod/tigron/test/command.go
  mod/tigron/test/helpers.go
  pkg/testutil/nerdtest/command.go
  pkg/testutil/nerdtest/utilities.go
Labels: area/ci

#4105 [DOC]: mod/tigron/require documentation
  mod/tigron/require/doc.md
Labels: documentation, area/ci

#4111 [CI]: quality of life: minor debugging output fixes
  mod/tigron/internal/com/command.go
  mod/tigron/internal/formatter/formatter.go
  mod/tigron/test/case.go
  mod/tigron/test/command.go
  pkg/testutil/nerdtest/command.go
Labels: area/ci

#4127 [PRIORITY] [CI]: Fix EL8 tests execution
  .github/workflows/test.yml
Labels: area/ci

#4130 [CI]: increase test timeout for EL8
  pkg/testutil/nerdtest/utilities_linux.go
Labels: area/ci

#4134 Mark kube target as flaky
  .github/workflows/test-kube.yml
Labels: area/ci, area/kubernetes

#4135 [CI]: bump kind version 0.27
  hack/build-integration-kubernetes.sh
Labels: area/ci, area/kubernetes

#4122 [CI]: rewrite some container and compose tests
  cmd/nerdctl/compose/compose_build_linux_test.go
  cmd/nerdctl/compose/compose_config_test.go
  cmd/nerdctl/compose/compose_cp_linux_test.go
  cmd/nerdctl/compose/compose_create_linux_test.go
  cmd/nerdctl/compose/compose_exec_linux_test.go
  cmd/nerdctl/compose/compose_run_linux_test.go
  cmd/nerdctl/container/container_logs_test.go
  cmd/nerdctl/container/container_run_network_linux_test.go
  cmd/nerdctl/container/container_run_soci_linux_test.go
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/container/container_run_verify_linux_test.go
  cmd/nerdctl/helpers/testing_linux.go
  cmd/nerdctl/image/image_encrypt_linux_test.go
  cmd/nerdctl/image/image_pull_linux_test.go
  cmd/nerdctl/ipfs/ipfs_simple_linux_test.go
  cmd/nerdctl/network/network_create_linux_test.go
  pkg/testutil/nerdtest/utilities.go
  pkg/testutil/testutil.go
  pkg/testutil/testutil_freebsd.go
  pkg/testutil/testutil_linux.go
  pkg/testutil/testutil_windows.go
Labels: area/ci

#4139 [CI]: extend CI timeout for tigron on windows which occasionally goes over
  .github/workflows/tigron.yml
Labels: area/ci, platform/Windows/Non-WSL2

#4136 [Tigron]: support multi-parameters for `expect.Contains` and `expect.DoesNotContain`
  cmd/nerdctl/completion/completion_test.go
  cmd/nerdctl/compose/compose_build_linux_test.go
  cmd/nerdctl/compose/compose_config_test.go
  cmd/nerdctl/compose/compose_exec_linux_test.go
  cmd/nerdctl/container/container_diff_test.go
  cmd/nerdctl/container/container_logs_test.go
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/image/image_list_test.go
  cmd/nerdctl/image/image_remove_test.go
  cmd/nerdctl/volume/volume_inspect_test.go
  cmd/nerdctl/volume/volume_prune_linux_test.go
  mod/tigron/expect/comparators.go
  mod/tigron/expect/comparators_test.go
  mod/tigron/expect/doc.md
Labels: area/ci

#4138 [Tigron]: `x509` helper
  mod/tigron/utils/testca/ca.go
  pkg/containerdutil/image_store.go
  pkg/testutil/nerdtest/ca/ca.go
  pkg/testutil/nerdtest/registry/cesanta.go
  pkg/testutil/nerdtest/registry/docker.go
  pkg/testutil/nerdtest/registry/kubo.go
  pkg/testutil/nerdtest/third-party.go
Labels: area/ci

#4155 [Tigron]: shorten max lines in logs to 50 and add message
  mod/tigron/internal/formatter/formatter.go
Labels: area/ci

#4159 [CI]: cleanup, breakout 1: `./hack`
  .github/workflows/lint.yml
  .github/workflows/test-canary.yml
  .github/workflows/test-kube.yml
  .github/workflows/test.yml
  .github/workflows/tigron.yml
  hack/build-integration-canary.sh
  hack/provisioning/README.md
  hack/provisioning/kube/kind.sh
  hack/provisioning/kube/kind.yaml
  hack/provisioning/linux/cni.sh
  hack/provisioning/linux/containerd.sh
  hack/provisioning/version/fetch.sh
  hack/provisioning/windows/cni.sh
  hack/provisioning/windows/containerd.ps1
  hack/scripts/lib.sh
Labels: area/ci

#4166 [QOL]: enhance error information for failing logURI
  pkg/cioutil/container_io.go
Labels: area/logging

#4009 feat: add --details flag to logs command
  cmd/nerdctl/container/container_logs.go
  cmd/nerdctl/container/container_logs_test.go
  docs/command-reference.md
  pkg/api/types/container_types.go
  pkg/cmd/container/logs.go
  pkg/logging/detail_writer.go
  pkg/logging/journald_logger.go
  pkg/logging/json_logger.go
  pkg/logging/log_viewer.go
  pkg/logging/logging.go
Labels: area/logging

#4160 [CI]: cleanup, breakout 2: small cleanups and fixes
  .github/workflows/lint.yml
  .github/workflows/project.yml
  .github/workflows/release.yml
  .github/workflows/test-canary.yml
  .github/workflows/test.yml
  .github/workflows/tigron.yml
Labels: area/ci
