Repository containerd/nerdctl, pull requests merged in 2025-02, with the labels that each got.

#3843 Harden journald test
  cmd/nerdctl/container/container_logs_test.go
  cmd/nerdctl/container/container_run_test.go
Labels: area/ci, area/logging

#3879 docs(nerdctl-compose): add missing details in command-reference.md
  docs/command-reference.md
Labels: documentation, area/compose

#3905 docs: add --log-driver=none to run command reference
  docs/command-reference.md
Labels: documentation, area/logging

#3850 Cleanup XDGRuntime
  pkg/buildkitutil/buildkitutil_freebsd.go
  pkg/buildkitutil/buildkitutil_linux.go
  pkg/buildkitutil/buildkitutil_unix.go
  pkg/bypass4netnsutil/bypass4netnsutil.go
  pkg/defaults/defaults_freebsd.go
  pkg/defaults/defaults_linux.go
  pkg/defaults/defaults_windows.go
  pkg/netutil/netutil_unix.go
  pkg/rootlessutil/xdg_linux.go
Labels: kind/refactor

#3919 CI: remove unbuffer from container tests
  cmd/nerdctl/container/container_exec_linux_test.go
  cmd/nerdctl/container/container_logs_test.go
  cmd/nerdctl/container/container_run_linux_test.go
Labels: area/ci

#3889 CI: make the `test` framework usable standalone in other projects
  go.mod
  pkg/testutil/test/LICENSE
  pkg/testutil/test/Makefile
  pkg/testutil/test/README.md
  pkg/testutil/test/go.mod
  pkg/testutil/test/go.sum
  pkg/testutil/test/hack/dev-setup-linux.sh
  pkg/testutil/test/hack/dev-setup-macos.sh
  pkg/testutil/test/hack/headers/bash.txt
  pkg/testutil/test/hack/headers/dockerfile.txt
  pkg/testutil/test/hack/headers/go.txt
  pkg/testutil/test/hack/headers/makefile.txt
  pkg/testutil/test/hack/make-lint-licenses.sh
  pkg/testutil/test/internal/pty/pty_darwin.go
Labels: area/ci

#3918 CI: rewrite signal tests
  cmd/nerdctl/container/container_restart_linux_test.go
  cmd/nerdctl/container/container_run_linux_test.go
  cmd/nerdctl/container/container_stop_linux_test.go
  pkg/testutil/nerdtest/utilities_linux.go
  pkg/testutil/test/command.go
  pkg/testutil/test/test.go
  pkg/testutil/testutil_linux.go
Labels: area/ci

#3931 Increase CI run timeout
  .github/workflows/test-canary.yml
  .github/workflows/test.yml
Labels: area/ci

#3911 CI: goimports-reviser: remove hack
  Makefile
  hack/lint-imports.sh
Labels: area/ci

#3930 CI: arm64-8core-32gb -> ubuntu-24.04-arm
  .github/workflows/test.yml
Labels: area/ci

#3934 Enforce pkg isolation as part of golangci
  .github/workflows/project.yml
  .golangci.yml
  hack/verify-pkg-isolation.sh
Labels: area/ci
