Repository containerd/nerdctl, pull requests merged in 2025-03, with the labels that each got.

#3915 CI: disable golangci preflight config validation
  .github/workflows/lint.yml
Labels: area/ci

#3953 Harden test pty error handling
  mod/tigron/test/command.go
Labels: area/ci

#3958 Add qemu/rosetta notes
  docs/multi-platform.md
Labels: documentation

#3910 CI: test framework, part III
  go.mod
  go.sum
  mod/tigron/.golangci.yml
  mod/tigron/.yamllint
  mod/tigron/Makefile
  mod/tigron/go.mod
  mod/tigron/go.sum
  mod/tigron/require/requirement.go
  mod/tigron/test/case.go
  mod/tigron/test/command.go
  mod/tigron/test/config.go
  mod/tigron/test/data.go
  mod/tigron/test/expected.go
  mod/tigron/test/helpers.go
  mod/tigron/test/interfaces.go
  mod/tigron/test/internal/pty/pty.go
  mod/tigron/test/internal/pty/pty_darwin.go
  mod/tigron/test/internal/pty/pty_freebsd.go
  mod/tigron/test/internal/pty/pty_linux.go
  mod/tigron/test/internal/pty/pty_windows.go
  mod/tigron/test/test.go
  mod/tigron/utils/utilities.go
Labels: area/ci

#3904 CI: drop Ubuntu 20.04, add AlmaLinux 8
  .github/workflows/test.yml
  cmd/nerdctl/container/container_run_cgroup_linux_test.go
  cmd/nerdctl/container/container_stats_test.go
Labels: area/ci

#3976 Update containerd/project-checks (1.2.2)
  .github/workflows/project.yml
Labels: priority/high, area/ci

#3979 Increase wait for ensurecontainerstarted
  pkg/testutil/nerdtest/utilities.go
Labels: area/ci

#3940 Adding document analyzing CI/dockerfile
  docs/dev/auditing_dockerfile.md
Labels: documentation, area/ci

#3964 --quiet image pulls in tests
  cmd/nerdctl/container/container_list_linux_test.go
  cmd/nerdctl/container/container_list_windows_test.go
  cmd/nerdctl/container/container_run_linux_test.go
  cmd/nerdctl/container/container_run_log_driver_syslog_test.go
  cmd/nerdctl/container/container_run_test.go
  cmd/nerdctl/container/container_run_user_linux_test.go
  cmd/nerdctl/container/multi_platform_linux_test.go
  cmd/nerdctl/image/image_inspect_test.go
  cmd/nerdctl/image/image_load_test.go
  cmd/nerdctl/image/image_pull_linux_test.go
  cmd/nerdctl/image/image_remove_test.go
  cmd/nerdctl/ipfs/ipfs_kubo_linux_test.go
  cmd/nerdctl/ipfs/ipfs_simple_linux_test.go
  cmd/nerdctl/issues/issues_linux_test.go
Labels: area/ci

#3993 CI: simplify setting up Lima
  .github/workflows/test.yml
Labels: area/ci

#3978 Replace hack/verify-no-patent.sh with depguard
  .github/workflows/project.yml
  .golangci.yml
  hack/verify-no-patent.sh
Labels: area/ci, easy-to-review

#3983 CI, build 1: disable buildx output for dependency stage
  .github/workflows/test.yml
Labels: area/ci

#3997 Dockerfile: remove "goversion" stage
  Dockerfile
Labels: area/ci

#3995 [carry #2337] ensure logger completion after container exit
  cmd/nerdctl/container/container_logs_test.go
  pkg/cmd/container/logs.go
  pkg/logging/logging.go
  pkg/logging/logging_test.go
Labels: area/logging

#3999 update RootlessKit (2.3.4)
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.3.2
  Dockerfile.d/SHA256SUMS.d/rootlesskit-v2.3.4
  go.mod
  go.sum
Labels: area/rootless

#3989 CI: update Canary and EL8 titles
  .github/workflows/test-canary.yml
  .github/workflows/test.yml
Labels: area/ci

#3985 CI, build 3: Stop sharding cache on containerd version
  .github/workflows/test.yml
Labels: area/ci

#4002 fix: none log driver creating log uri
  cmd/nerdctl/container/container_logs_test.go
  pkg/cioutil/container_io.go
  pkg/cmd/container/create.go
  pkg/taskutil/taskutil.go
Labels: area/logging

#4042 [CI] Tigron breakout 2: remove gotest.tools assert dependency internally
  mod/tigron/expect/comparators.go
  mod/tigron/internal/assertive/assertive.go
  mod/tigron/internal/assertive/assertive_test.go
  mod/tigron/internal/assertive/doc.go
  mod/tigron/test/case.go
  mod/tigron/test/command.go
Labels: area/ci

#4048 [CI] Update golangci to v2
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  cmd/nerdctl/container/container_inspect_linux_test.go
  pkg/cmd/container/run_mount.go
  pkg/logging/logging.go
Labels: area/ci

#4051 [CI] golangci v2: review, fix, document, rules
  .golangci.yml
  cmd/nerdctl/container/container_update.go
  cmd/nerdctl/inspect/inspect.go
  pkg/api/types/image_types.go
  pkg/cmd/container/run_windows.go
  pkg/cmd/network/list.go
  pkg/containerutil/container_network_manager.go
  pkg/dnsutil/hostsstore/hosts.go
  pkg/imgutil/commit/commit.go
  pkg/imgutil/filtering.go
  pkg/infoutil/infoutilmock/infoutil_mock.go
  pkg/inspecttypes/dockercompat/dockercompat.go
  pkg/netutil/netutil_test.go
Labels: area/ci
